// SPDX-FileCopyrightText: Copyright (c) 2026 Mike Li/Mikewolfli/Wei Li(mikewolfli@163.com)
// SPDX-License-Identifier: MIT

//! Control backend abstraction for native and custom-painted control paths.
//!
//! AUTO-GENERATED by tools/split_control_backend.py — do not edit manually.
//! Generated from implementation.rs.

/// Custom-painted control backend: widgets are drawn by this library rather than
/// mapped onto platform controls. Compiled only with the `controls-custom`
/// feature.
pub mod custom;
/// Process-wide backend selection: [`get_control_backend`] and the per-widget
/// routing policy.
pub mod dispatcher;
#[cfg(not(alloc_frugal))]
/// Native control backend: forwards to the active [`crate::platform`] host.
pub mod native;
/// Maps a widget kind to the backend that must paint it.
pub mod routing;
/// The [`trait_def::ControlBackend`] contract and its default implementations.
pub mod trait_def;
/// Backend kind and route-preference enums shared by the backends.
pub mod types;

// Re-export key public types for backward compatibility.
#[cfg(feature = "controls-custom")]
pub use custom::CustomPaintControlBackend;
pub use dispatcher::{active_control_policy, get_control_backend, get_control_backend_for_widget};
#[cfg(not(alloc_frugal))]
pub use native::NativeControlBackend;
pub use routing::route_preference_for_widget_kind;
pub use trait_def::ControlBackend;
pub use types::{ControlBackendKind, ControlRoutePreference};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn control_backend_kind_re_exported() {
        let _native = ControlBackendKind::Native;
        let _custom = ControlBackendKind::Custom;
        assert_ne!(_native, _custom);
    }

    #[test]
    fn control_route_preference_re_exported() {
        let _native_pref = ControlRoutePreference::NativePreferred;
        let _custom_req = ControlRoutePreference::CustomRequired;
        assert_ne!(_native_pref, _custom_req);
    }

    #[cfg(not(alloc_frugal))]
    #[test]
    fn route_preference_for_widget_kind_re_exported() {
        use crate::widget::WidgetKind;
        // Every kind resolves to the library-held mechanism, in every profile: the
        // platform no longer offers controls to map onto, so there is nothing left
        // for this policy to choose between (BLUE15 rule #55). The sample uses kinds
        // that exist in every profile, so this does not need a `cfg` of its own.
        for kind in [WidgetKind::Button, WidgetKind::Label] {
            assert_eq!(
                route_preference_for_widget_kind(kind),
                ControlRoutePreference::CustomRequired,
                "WidgetKind::{kind:?} must be painted by the library",
            );
        }
    }

    #[test]
    fn control_backend_trait_re_exported() {
        // ControlBackend is a trait — verify it can be used as a trait object.
        fn _take_trait_object(_: &dyn ControlBackend) {}
        let _ = _take_trait_object;
    }

    #[cfg(not(alloc_frugal))]
    #[test]
    fn native_control_backend_re_exported() {
        let backend = NativeControlBackend::new();
        assert_eq!(backend.backend_name(), "native-control-backend");
    }

    #[test]
    fn dispatcher_functions_re_exported() {
        let backend = get_control_backend();
        assert!(!backend.backend_name().is_empty());
        let policy = active_control_policy();
        assert!(!policy.is_empty());
        use crate::widget::WidgetKind;
        let backend_for_widget = get_control_backend_for_widget(WidgetKind::Button);
        assert!(!backend_for_widget.backend_name().is_empty());
    }

    #[test]
    #[cfg(feature = "controls-custom")]
    fn custom_paint_control_backend_re_exported() {
        let backend = CustomPaintControlBackend::new();
        assert_eq!(backend.backend_name(), "custom-paint-control-backend");
    }
}
