//! Control backend abstraction for native and custom-painted control paths.
//!
//! AUTO-GENERATED by tools/split_control_backend.py — do not edit manually.
//! Generated from implementation.rs.

pub mod types;
pub mod routing;
pub mod trait_def;
pub mod native;
pub mod custom;
pub mod dispatcher;

// Re-export key public types for backward compatibility.
pub use types::{ControlBackendKind, ControlRoutePreference};
pub use routing::route_preference_for_widget_kind;
pub use trait_def::ControlBackend;
pub use native::NativeControlBackend;
pub use dispatcher::{get_control_backend, get_control_backend_for_widget, active_control_policy};
#[cfg(feature = "controls-custom")]
pub use custom::CustomPaintControlBackend;
