#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 Mike Li/Mikewolfli/Wei Li(mikewolfli@163.com)
# SPDX-License-Identifier: MIT

"""Rewrite the custom backend's `create_*` bodies to mount a real widget.

BLUE15 Phase C-2/C-3. Each `create_*` used to allocate an id, write text and
geometry into six shadow maps, and return an id that addressed no widget object.
That made every property answer from a copy of the widget's own fields and made
the control impossible to paint. The replacement body builds the widget through
`WidgetFactory` and hands ownership to `widget::runtime`, so the returned id
addresses the live control.

The transformation is mechanical because the bodies are generated by a macro and
follow one shape:

    fn create_x(&self, ..) -> ObjectId {
        let widget_id = self.alloc_widget_id();
        let mut state = self.state.lock()...;
        state.texts.insert(widget_id, text.to_string());
        ... five more map inserts ...
        state.widget_properties.insert(widget_id, CustomWidgetProperties { .. });
        widget_id
    }

becomes

    fn create_x(&self, ..) -> ObjectId {
        self.mount_widget_of_kind(WidgetKind::X, text, x, y, width, height)
    }

The kind is taken from the `widget_kind: WidgetKind::X` field already present in the
body, so the rewrite cannot guess wrong. A method whose body does not match the
expected shape is reported and left untouched for manual review.

One-shot migration tool: deleted once the rewrite is verified.
"""

import re
import sys

SIGNATURE = re.compile(
    r"^(?P<indent>\s*)(?P<sig>fn (?P<name>create_\w+)\(\s*&self,\s*"
    r"(?P<args>(?:[^()]|\([^()]*\))*?)\)\s*->\s*ObjectId\s*\{)",
    re.MULTILINE | re.DOTALL,
)
WIDGET_KIND = re.compile(r"widget_kind:\s*WidgetKind::(\w+)")
TEXT_ARG = re.compile(r"\btext\b")


def body_span(text, open_brace):
    """Return the index of the `}` matching the `{` at `open_brace`."""
    depth = 0
    i = open_brace
    while i < len(text):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return None


def process(path):
    with open(path, encoding="utf-8") as handle:
        text = handle.read()

    rewrites = []
    skipped = []

    for match in SIGNATURE.finditer(text):
        brace = text.index("{", match.end() - 1)
        close = body_span(text, brace)
        if close is None:
            skipped.append((match.group("name"), "unbalanced braces"))
            continue

        body = text[brace + 1 : close]
        kind = WIDGET_KIND.search(body)
        if not kind:
            skipped.append((match.group("name"), "no WidgetKind in body"))
            continue

        kind_name = kind.group(1)
        args = match.group("args")
        # The payload parameter's real name varies (`text`, `title`). Take the
        # *identifier* of the second parameter (after `&self`) and use it verbatim.
        params = [p.strip() for p in args.split(",") if p.strip()]
        # The regex consumes `&self`, so `params[0]` is the first real parameter.
        # It is `parent` for every widget constructor except `create_window`,
        # which is a root and has none.
        parent_param = "0"
        payload_index = 0
        if params and params[0].split(":", 1)[0].strip() == "parent":
            parent_param = "parent"
            payload_index = 1

        if len(params) <= payload_index:
            # Geometry-only method: no payload string. `mount_widget_of_kind`
            # accepts `&str`, so pass the empty string the factory expects.
            text_param = '""'
        else:
            payload_decl = params[payload_index]
            if ":" not in payload_decl:
                skipped.append((match.group("name"), f"unparsable payload arg {payload_decl!r}"))
                continue
            candidate = payload_decl.split(":", 1)[0].strip()
            if TEXT_ARG.fullmatch(candidate) or candidate in ("title", "label", "caption"):
                text_param = candidate
            else:
                # A non-string parameter in the payload slot means this method has
                # geometry only; the factory receives the empty string.
                text_param = '""'

        rewrites.append(
            (brace, close, match.group("indent"), kind_name, parent_param, text_param)
        )

    if not rewrites:
        return 0, skipped

    for brace, close, indent, kind_name, parent_param, text_param in reversed(rewrites):
        replacement = (
            f"\n{indent}    self.mount_widget_of_kind("
            f"WidgetKind::{kind_name}, {parent_param}, {text_param}, x, y, width, height)\n{indent}"
        )
        text = text[: brace + 1] + replacement + text[close:]

    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)
    return len(rewrites), skipped


def main():
    total = 0
    for path in sys.argv[1:]:
        count, skipped = process(path)
        if count:
            total += count
            print(f"{count:3d}  {path}")
        for name, reason in skipped:
            print(f"  SKIP {name}: {reason}")
    print(f"\n{total} create_* methods rewritten")


if __name__ == "__main__":
    main()
