// SPDX-FileCopyrightText: Copyright (c) 2026 Mike Li/Mikewolfli/Wei Li(mikewolfli@163.com)
// SPDX-License-Identifier: MIT
//
// GENERATED by tools/gen_emoji_subset.py -- do not edit by hand.
//
// Noto Color Emoji -- colour-emoji subset (colour emoji as CBDT PNG bitmaps, one strike at 109 ppem)
//     Project:  https://raw.githubusercontent.com/googlefonts/noto-emoji
//     Source:   https://raw.githubusercontent.com/googlefonts/noto-emoji/main/2D/fonts/NotoColorEmoji-flagsonly.ttf
//     SHA-256 (upstream .ttf): 6d3b266ee9631119cd6fea9eea7ea2226874a441532e18908c5b839322f3c5dd
//     Licence:  OFL-1.1
//     Subset:   36 codepoints, 872100 bytes
//
// This file is a **Modified Version** within the meaning of the SIL Open Font License, Version
// 1.1: it retains the upstream colour bitmaps verbatim, as a subset. It does not use the
// upstream Reserved Font Name.
//
// The payload is a binary `include_bytes!` rather than a Rust array: 872100 bytes written
// as `0x00,` literals would be several times this file's size, which is a worse artifact than the
// binary it describes. See the repository-root `NOTICE`.

/// The generated subset's bytes, in the binary's read-only section.
pub const FONT: &[u8] = include_bytes!("emoji.ttf");
