// SPDX-FileCopyrightText: Copyright (c) 2026 Mike Li/Mikewolfli/Wei Li(mikewolfli@163.com)
// SPDX-License-Identifier: MIT

// The declared payload of every published capability event — **generated**.
//
// # Why this is generated and not hand-written
//
// BLUE19 rule #95 makes the event side of a capability carry a type, the way the property side
// carries `PropertyValueKind`. There are 326 `(control, event)` pairs; a hand-written table that
// size would be a second source of truth for 186 names, and would drift from the signals on the
// first rename. This table is derived from the real signal declarations by
// `tools/derive_event_payloads.py` and re-derived, independently, by
// `tools/check_event_payload_types.py` — so an edit that disagrees with the signal fails a gate
// instead of quietly misinforming a designer.
//
// Ordinary comments rather than `//!` doc comments because this file is `include!`-ed into
// `properties.rs` mid-module, where an inner doc comment is a compile error.
//
// Regenerate with: `python3 tools/derive_event_payloads.py`.

use super::types::{EventPayloadShape as S, EventSchema};
use super::PropertyValueKind as K;

/// The published events of one control, with their payload types.
///
/// # Why a macro and not 187 hand-written slices
///
/// The names and the payloads are one table because they are one fact: a name without its type is
/// exactly what a designer cannot use. A capability therefore looks its events up instead of
/// re-spelling them:
///
/// ```ignore
/// events: events_of!("button"),
/// ```
///
/// Two things that could drift apart — the list of names a capability publishes and the payload
/// each name carries — are then one row, and the row is derived from the signal.
///
/// # How the lookup stays a compile-time check
///
/// The expansion indexes [`EVENT_SCHEMAS`] with the span [`CONTROL_STARTS`] records for this
/// control, so it is a bounds-checked slice of a `static`: a control whose span is wrong, or that
/// is absent from [`CONTROL_STARTS`], fails to compile rather than publishing less than it says.
macro_rules! events_of {
    ($control:literal) => {{
        const ROW: usize = {
            let mut i = 0usize;
            let mut found = usize::MAX;
            while i < CONTROL_STARTS.len() {
                if str_eq(CONTROL_STARTS[i].0, $control) {
                    found = i;
                    break;
                }
                i += 1;
            }
            if found == usize::MAX {
                panic!("no events derived for this control — run tools/derive_event_payloads.py");
            }
            found
        };
        let (_control, start, len) = CONTROL_STARTS[ROW];
        // `start`/`len` are already absolute indices into `EVENT_SCHEMAS`: the table records the
        // control's own start, and its events occupy the immediately following `len` rows. An
        // earlier revision also carried a `ROW_ROWS` table to translate "start" into an index,
        // which was an identity table of 332 entries (`[0, 1, 2, …, 331]`) — a second copy of
        // `0..n` that had to be regenerated in lockstep and could only ever be wrong. `start` is
        // already the answer.
        &EVENT_SCHEMAS[start..start + len]
    }};
}

/// Compile-time string equality, for the macro's control lookup.
///
/// Rust has no `const` `str::eq`, and the alternatives are worse: `match` on string literals is
/// not const either, and emitting 162 named constants would make the table unreadable. Walking the
/// bytes is a handful of instructions, all resolved at compile time.
const fn str_eq(a: &str, b: &str) -> bool {
    let (a, b) = (a.as_bytes(), b.as_bytes());
    if a.len() != b.len() {
        return false;
    }
    let mut i = 0;
    while i < a.len() {
        if a[i] != b[i] {
            return false;
        }
        i += 1;
    }
    true
}

/// Every published event of every control, in `(control, event)` order.
///
/// The rows are [`EventSchema`] values rather than the raw kind and shape, so `events_of!` returns
/// the slice a capability can use directly and the macro does no conversion at the call site.
pub(crate) static EVENT_SCHEMAS: &[EventSchema] = &[
    EventSchema { name: "changed", payload: None, shape: None },
    EventSchema { name: "hovered", payload: None, shape: None },
    EventSchema { name: "toggled", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "triggered", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "nav_selected", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "animation_finished", payload: None, shape: None },
    EventSchema { name: "frame_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "action_pressed", payload: None, shape: None },
    EventSchema { name: "back_pressed", payload: None, shape: None },
    EventSchema { name: "changed", payload: None, shape: None },
    EventSchema { name: "suggestion_selected", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "text_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "action_clicked", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "dismissed", payload: None, shape: None },
    EventSchema { name: "barcode_detected", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "curve_changed", payload: Some(K::String), shape: Some(S::Mixed) },
    EventSchema { name: "selected_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "dismissed", payload: None, shape: None },
    EventSchema { name: "segment_activated", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "canceled", payload: None, shape: None },
    EventSchema { name: "clicked", payload: None, shape: None },
    EventSchema { name: "pressed", payload: None, shape: None },
    EventSchema { name: "released", payload: None, shape: None },
    EventSchema { name: "state_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "selection_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "bar_clicked", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "bar_hovered", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "bar_unhovered", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "double_clicked", payload: None, shape: None },
    EventSchema { name: "mouse_moved", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "mouse_pressed", payload: None, shape: None },
    EventSchema { name: "mouse_released", payload: None, shape: None },
    EventSchema { name: "page_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "selection_changed", payload: Some(K::UInt), shape: Some(S::ListScalar) },
    EventSchema { name: "data_point_clicked", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "data_point_hovered", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "data_point_unhovered", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "state_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "toggled", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "chip_toggled", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "completion_changed", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "cursor_moved", payload: Some(K::UInt), shape: Some(S::Tuple2) },
    EventSchema { name: "fold_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "search_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "selection_changed", payload: Some(K::Rect), shape: Some(S::OptionalScalar) },
    EventSchema { name: "tab_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "text_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "toggled", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "accepted", payload: None, shape: None },
    EventSchema { name: "color_selected", payload: Some(K::Color), shape: Some(S::Scalar) },
    EventSchema { name: "rejected", payload: None, shape: None },
    EventSchema { name: "color_hovered", payload: Some(K::Color), shape: Some(S::Scalar) },
    EventSchema { name: "color_selected", payload: Some(K::Color), shape: Some(S::Scalar) },
    EventSchema { name: "color_changed", payload: Some(K::Color), shape: Some(S::Scalar) },
    EventSchema { name: "hex_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "clicked", payload: None, shape: None },
    EventSchema { name: "activated", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "current_index_changed", payload: Some(K::UInt), shape: Some(S::OptionalScalar) },
    EventSchema { name: "current_text_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "popup_visibility_changed", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "clicked", payload: None, shape: None },
    EventSchema { name: "hovered", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "command_activated", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "query_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "cancelled", payload: None, shape: None },
    EventSchema { name: "confirmed", payload: None, shape: None },
    EventSchema { name: "date_changed", payload: Some(K::String), shape: Some(S::Mixed) },
    EventSchema { name: "back_pressed", payload: None, shape: None },
    EventSchema { name: "value_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "value_changed", payload: Some(K::Float), shape: Some(S::Scalar) },
    EventSchema { name: "toggled", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "visible_window_changed", payload: Some(K::UInt), shape: Some(S::Tuple4) },
    EventSchema { name: "selection_changed", payload: Some(K::UInt), shape: Some(S::OptionalScalar) },
    EventSchema { name: "visible_window_changed", payload: Some(K::UInt), shape: Some(S::Tuple2) },
    EventSchema { name: "date_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "range_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "datetime_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "level_hovered", payload: Some(K::Float), shape: Some(S::Scalar) },
    EventSchema { name: "slider_pressed", payload: None, shape: None },
    EventSchema { name: "slider_released", payload: None, shape: None },
    EventSchema { name: "value_changed", payload: Some(K::Int), shape: Some(S::Scalar) },
    EventSchema { name: "accepted", payload: None, shape: None },
    EventSchema { name: "closed", payload: None, shape: None },
    EventSchema { name: "opened", payload: None, shape: None },
    EventSchema { name: "rejected", payload: None, shape: None },
    EventSchema { name: "compared", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "dock_location_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "features_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "top_level_changed", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "payload_dropped", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "changed", payload: None, shape: None },
    EventSchema { name: "item_selected", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "item_selected", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "text_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "glyph_chosen", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "action_pressed", payload: None, shape: None },
    EventSchema { name: "clicked", payload: None, shape: None },
    EventSchema { name: "accepted", payload: None, shape: None },
    EventSchema { name: "current_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "file_selected", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "files_selected", payload: Some(K::String), shape: Some(S::ListScalar) },
    EventSchema { name: "rejected", payload: None, shape: None },
    EventSchema { name: "close", payload: None, shape: None },
    EventSchema { name: "find_next", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "find_previous", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "replace", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "replace_all", payload: Some(K::String), shape: Some(S::Tuple3) },
    EventSchema { name: "text_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "activated", payload: Some(K::Int), shape: Some(S::Scalar) },
    EventSchema { name: "current_font_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "current_index_changed", payload: Some(K::Int), shape: Some(S::Scalar) },
    EventSchema { name: "popup_hidden", payload: None, shape: None },
    EventSchema { name: "popup_shown", payload: None, shape: None },
    EventSchema { name: "text_edited", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "accepted", payload: None, shape: None },
    EventSchema { name: "font_selected", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "rejected", payload: None, shape: None },
    EventSchema { name: "clicked", payload: None, shape: None },
    EventSchema { name: "hovered_changed", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "pressed_changed", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "task_selected", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "cell_clicked", payload: Some(K::UInt), shape: Some(S::Tuple2) },
    EventSchema { name: "cell_hovered", payload: Some(K::UInt), shape: Some(S::Tuple2) },
    EventSchema { name: "cell_double_clicked", payload: Some(K::UInt), shape: Some(S::Tuple2) },
    EventSchema { name: "cell_selected", payload: Some(K::UInt), shape: Some(S::Tuple2) },
    EventSchema { name: "header_clicked", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "sort_changed", payload: Some(K::String), shape: Some(S::Mixed) },
    EventSchema { name: "toggled", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "cell_clicked", payload: Some(K::UInt), shape: Some(S::Tuple2) },
    EventSchema { name: "cell_hovered", payload: Some(K::UInt), shape: Some(S::Tuple2) },
    EventSchema { name: "animation_completed", payload: None, shape: None },
    EventSchema { name: "image_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "bar_clicked", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "bar_hovered", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "edit_accepted", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "edit_cancelled", payload: None, shape: None },
    EventSchema { name: "accepted", payload: None, shape: None },
    EventSchema { name: "double_value_changed", payload: Some(K::Float), shape: Some(S::Scalar) },
    EventSchema { name: "int_value_changed", payload: Some(K::Int), shape: Some(S::Scalar) },
    EventSchema { name: "rejected", payload: None, shape: None },
    EventSchema { name: "text_value_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "card_activated", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "card_moved", payload: Some(K::String), shape: Some(S::Tuple2) },
    EventSchema { name: "backspace_pressed", payload: None, shape: None },
    EventSchema { name: "enter_pressed", payload: None, shape: None },
    EventSchema { name: "key_pressed", payload: Some(K::UInt), shape: Some(S::Tuple2) },
    EventSchema { name: "space_pressed", payload: None, shape: None },
    EventSchema { name: "overflow", payload: None, shape: None },
    EventSchema { name: "value_changed", payload: Some(K::Float), shape: Some(S::Scalar) },
    EventSchema { name: "editing_finished", payload: None, shape: None },
    EventSchema { name: "return_pressed", payload: None, shape: None },
    EventSchema { name: "text_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "item_activated", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "item_selected", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "selection_changed", payload: None, shape: None },
    EventSchema { name: "focused_row_changed", payload: Some(K::UInt), shape: Some(S::OptionalScalar) },
    EventSchema { name: "selection_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "animation_finished", payload: None, shape: None },
    EventSchema { name: "center_changed", payload: Some(K::Float), shape: Some(S::Tuple2) },
    EventSchema { name: "marker_selected", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "zoom_changed", payload: Some(K::Float), shape: Some(S::Scalar) },
    EventSchema { name: "preview_mode_changed", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "text_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "text_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "selected_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "action_pressed", payload: None, shape: None },
    EventSchema { name: "dismissed", payload: None, shape: None },
    EventSchema { name: "subwindow_activated", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "playback_changed", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "position_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "source_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "volume_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "mention_inserted", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "popup_toggled", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "text_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "about_to_hide", payload: None, shape: None },
    EventSchema { name: "about_to_show", payload: None, shape: None },
    EventSchema { name: "submenu_requested", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "triggered", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "triggered_index", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "hovered_entry", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "triggered", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "item_triggered", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "accepted", payload: None, shape: None },
    EventSchema { name: "button_clicked", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "rejected", payload: None, shape: None },
    EventSchema { name: "changed", payload: None, shape: None },
    EventSchema { name: "clicked", payload: None, shape: None },
    EventSchema { name: "mouse_pressed", payload: None, shape: None },
    EventSchema { name: "mouse_released", payload: None, shape: None },
    EventSchema { name: "date_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "dismissed", payload: None, shape: None },
    EventSchema { name: "selection_changed", payload: Some(K::UInt), shape: Some(S::ListScalar) },
    EventSchema { name: "closed", payload: None, shape: None },
    EventSchema { name: "item_selected", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "opened", payload: None, shape: None },
    EventSchema { name: "navigation_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "notification_activated", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "notification_selected", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "unread_count_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "value_changed", payload: Some(K::Int), shape: Some(S::Scalar) },
    EventSchema { name: "level_clicked", payload: Some(K::String), shape: Some(S::Mixed) },
    EventSchema { name: "level_hovered", payload: Some(K::String), shape: Some(S::Mixed) },
    EventSchema { name: "level_unhovered", payload: Some(K::String), shape: Some(S::Mixed) },
    EventSchema { name: "completed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "value_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "page_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "toggled", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "about_to_hide", payload: None, shape: None },
    EventSchema { name: "about_to_show", payload: None, shape: None },
    EventSchema { name: "triggered", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "triggered_text", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "closed", payload: None, shape: None },
    EventSchema { name: "opened", payload: None, shape: None },
    EventSchema { name: "value_changed", payload: Some(K::Int), shape: Some(S::Scalar) },
    EventSchema { name: "canceled", payload: None, shape: None },
    EventSchema { name: "property_changed", payload: Some(K::String), shape: Some(S::Tuple2) },
    EventSchema { name: "selected", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "query_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "quote_clicked", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "quote_hovered", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "selection_changed", payload: Some(K::String), shape: Some(S::OptionalScalar) },
    EventSchema { name: "axis_hovered", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "series_clicked", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "checked_changed", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "selected", payload: None, shape: None },
    EventSchema { name: "range_changed", payload: Some(K::Float), shape: Some(S::Tuple2) },
    EventSchema { name: "rating_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "refresh_triggered", payload: None, shape: None },
    EventSchema { name: "current_tab_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "item_triggered", payload: Some(K::UInt), shape: Some(S::Tuple3) },
    EventSchema { name: "cursor_position_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "read_only_changed", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "selection_changed", payload: Some(K::UInt), shape: Some(S::OptionalTuple2) },
    EventSchema { name: "text_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "animation_finished", payload: None, shape: None },
    EventSchema { name: "changed", payload: None, shape: None },
    EventSchema { name: "scroll_position_changed", payload: Some(K::Int), shape: Some(S::Tuple2) },
    EventSchema { name: "slider_moved", payload: Some(K::Int), shape: Some(S::Scalar) },
    EventSchema { name: "slider_pressed", payload: None, shape: None },
    EventSchema { name: "slider_released", payload: None, shape: None },
    EventSchema { name: "value_changed", payload: Some(K::Int), shape: Some(S::Scalar) },
    EventSchema { name: "canceled", payload: None, shape: None },
    EventSchema { name: "search_submitted", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "text_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "text_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "selected_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "selection_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "shortcut_changed", payload: Some(K::String), shape: Some(S::Mixed) },
    EventSchema { name: "changed", payload: None, shape: None },
    EventSchema { name: "stroke_completed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "slider_moved", payload: Some(K::Int), shape: Some(S::Scalar) },
    EventSchema { name: "slider_pressed", payload: None, shape: None },
    EventSchema { name: "slider_released", payload: None, shape: None },
    EventSchema { name: "value_changed", payload: Some(K::Int), shape: Some(S::Scalar) },
    EventSchema { name: "action_triggered", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "dismissed", payload: None, shape: None },
    EventSchema { name: "editing_finished", payload: None, shape: None },
    EventSchema { name: "value_changed", payload: Some(K::Int), shape: Some(S::Scalar) },
    EventSchema { name: "finished", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "skipped", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "action_selected", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "menu_toggled", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "triggered", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "orientation_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "pane_layout_changed", payload: Some(K::Float), shape: Some(S::ListScalar) },
    EventSchema { name: "current_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "message_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "value_changed", payload: Some(K::Int), shape: Some(S::Scalar) },
    EventSchema { name: "dismissed", payload: None, shape: None },
    EventSchema { name: "toggled", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "current_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "tab_close_requested", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "tab_moved", payload: Some(K::UInt), shape: Some(S::Tuple2) },
    EventSchema { name: "tab_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "current_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "tab_close_requested", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "tab_moved", payload: Some(K::UInt), shape: Some(S::Tuple2) },
    EventSchema { name: "focused_row_changed", payload: Some(K::UInt), shape: Some(S::OptionalScalar) },
    EventSchema { name: "selection_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "focused_row_changed", payload: Some(K::UInt), shape: Some(S::OptionalScalar) },
    EventSchema { name: "selection_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "tags_changed", payload: Some(K::String), shape: Some(S::ListScalar) },
    EventSchema { name: "command_submitted", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "changed", payload: None, shape: None },
    EventSchema { name: "text_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "popup_visibility_changed", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "time_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "item_selected", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "dismissed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "toast_activated", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "toast_dismissed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "checked_changed", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "pressed", payload: None, shape: None },
    EventSchema { name: "released", payload: None, shape: None },
    EventSchema { name: "state_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "toggled", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "action_triggered", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "orientation_changed", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "top_level_changed", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "visibility_changed", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "current_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "clicked", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "toggled", payload: Some(K::Bool), shape: Some(S::Scalar) },
    EventSchema { name: "triggered", payload: None, shape: None },
    EventSchema { name: "projection_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "selection_changed", payload: Some(K::UInt), shape: Some(S::OptionalScalar) },
    EventSchema { name: "focused_node_changed", payload: Some(K::UInt), shape: Some(S::OptionalScalar) },
    EventSchema { name: "selection_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "playback_ended", payload: None, shape: None },
    EventSchema { name: "playback_paused", payload: None, shape: None },
    EventSchema { name: "playback_started", payload: None, shape: None },
    EventSchema { name: "time_updated", payload: Some(K::Float), shape: Some(S::Scalar) },
    EventSchema { name: "selection_changed", payload: Some(K::UInt), shape: Some(S::OptionalScalar) },
    EventSchema { name: "visible_window_changed", payload: Some(K::UInt), shape: Some(S::Tuple2) },
    EventSchema { name: "visible_window_changed", payload: Some(K::UInt), shape: Some(S::Tuple4) },
    EventSchema { name: "bar_clicked", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "bar_hovered", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "certificate_error", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "console_message", payload: Some(K::String), shape: Some(S::Mixed) },
    EventSchema { name: "download_requested", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "error_occurred", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "loading_finished", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "loading_started", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "navigation_state_changed", payload: Some(K::Bool), shape: Some(S::Tuple2) },
    EventSchema { name: "page_created", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "page_destroyed", payload: Some(K::UInt), shape: Some(S::Scalar) },
    EventSchema { name: "title_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "url_changed", payload: Some(K::String), shape: Some(S::Scalar) },
    EventSchema { name: "closed", payload: None, shape: None },
    EventSchema { name: "cancelled", payload: None, shape: None },
    EventSchema { name: "finished", payload: None, shape: None },
    EventSchema { name: "step_changed", payload: Some(K::UInt), shape: Some(S::Scalar) },
];

/// `(control, schema start index, event count)` for every control that publishes an event.
///
/// The span into [`EVENT_SCHEMAS`] for one control, so `events_of!` costs one lookup and no
/// per-row filtering. `EVENT_SCHEMAS` is grouped by control (the generator sorts it), which is what
/// makes a span a contiguous range rather than a scatter.
pub(crate) static CONTROL_STARTS: &[(&str, usize, usize)] = &[
    ("action", 0, 4),
    ("adaptive_scaffold", 4, 1),
    ("animated_image", 5, 2),
    ("app_bar", 7, 2),
    ("arc", 9, 1),
    ("auto_complete_edit", 10, 2),
    ("banner", 12, 2),
    ("barcode_scanner", 14, 1),
    ("bezier_curve_editor", 15, 1),
    ("bottom_navigation_bar", 16, 1),
    ("bottom_sheet", 17, 1),
    ("breadcrumb", 18, 1),
    ("button", 19, 5),
    ("calendar", 24, 1),
    ("candlestick_chart", 25, 3),
    ("canvas", 28, 4),
    ("carousel", 32, 1),
    ("cascader", 33, 1),
    ("chart", 34, 3),
    ("check_box", 37, 2),
    ("chip", 39, 1),
    ("code_editor", 40, 7),
    ("collapsible_pane", 47, 1),
    ("color_dialog", 48, 3),
    ("color_history", 51, 2),
    ("color_picker", 53, 2),
    ("color_well", 55, 1),
    ("combo_box", 56, 4),
    ("command_link", 60, 2),
    ("command_palette", 62, 2),
    ("cupertino_alert_dialog", 64, 2),
    ("cupertino_date_picker", 66, 1),
    ("cupertino_navigation_bar", 67, 1),
    ("cupertino_segmented_control", 68, 1),
    ("cupertino_slider", 69, 1),
    ("cupertino_switch", 70, 1),
    ("data_grid", 71, 1),
    ("data_view", 72, 2),
    ("date_edit", 74, 1),
    ("date_range_picker", 75, 1),
    ("date_time_edit", 76, 1),
    ("depth_chart", 77, 1),
    ("dial", 78, 3),
    ("dialog", 81, 4),
    ("diff_viewer", 85, 1),
    ("dock_widget", 86, 3),
    ("drop_zone", 89, 1),
    ("dropdown", 90, 1),
    ("dropdown_menu", 91, 1),
    ("editable_combo_box", 92, 2),
    ("emoji_picker", 94, 1),
    ("empty_state", 95, 1),
    ("fab", 96, 1),
    ("file_dialog", 97, 5),
    ("find_replace_dialog", 102, 5),
    ("floating_label", 107, 1),
    ("font_combo_box", 108, 6),
    ("font_dialog", 114, 3),
    ("freeform_shape", 117, 3),
    ("gantt_widget", 120, 1),
    ("grid", 121, 2),
    ("grid_table", 123, 4),
    ("group_box", 127, 1),
    ("heatmap", 128, 2),
    ("hero_animation", 130, 1),
    ("image_gallery", 131, 1),
    ("indicator_chart", 132, 2),
    ("inplace_editor", 134, 2),
    ("input_dialog", 136, 5),
    ("kanban_board", 141, 2),
    ("keyboard", 143, 4),
    ("lcd_number", 147, 2),
    ("line_edit", 149, 3),
    ("list_box", 152, 3),
    ("list_view", 155, 2),
    ("lottie_widget", 157, 1),
    ("map_view", 158, 3),
    ("markdown_editor", 161, 2),
    ("masked_edit", 163, 1),
    ("material_navigation_rail", 164, 1),
    ("material_snackbar", 165, 2),
    ("mdi_area", 167, 1),
    ("media_player", 168, 4),
    ("mention", 172, 3),
    ("menu", 175, 5),
    ("menu_bar", 180, 2),
    ("menu_button", 182, 1),
    ("message_box", 183, 3),
    ("meter", 186, 1),
    ("mini_canvas", 187, 3),
    ("mobile_date_picker", 190, 1),
    ("modal_bottom_sheet", 191, 1),
    ("multi_select_combo_box", 192, 1),
    ("navigation_drawer", 193, 3),
    ("navigation_stack", 196, 1),
    ("notification_center", 197, 3),
    ("number_picker", 200, 1),
    ("order_book", 201, 3),
    ("otp_input", 204, 2),
    ("pagination", 206, 1),
    ("panel", 207, 1),
    ("pie_menu", 208, 4),
    ("popup_window", 212, 2),
    ("progress_bar", 214, 1),
    ("progress_dialog", 215, 1),
    ("properties_panel", 216, 1),
    ("property_grid", 217, 1),
    ("query_builder", 218, 1),
    ("quote_board", 219, 3),
    ("radar_chart", 222, 2),
    ("radio_button", 224, 2),
    ("range_slider", 226, 1),
    ("rating", 227, 1),
    ("refresh_control", 228, 1),
    ("ribbon_bar", 229, 2),
    ("rich_edit", 231, 4),
    ("rive_widget", 235, 1),
    ("roller", 236, 1),
    ("scroll_area", 237, 1),
    ("scroll_bar", 238, 4),
    ("search_bar", 242, 3),
    ("search_box", 245, 1),
    ("segmented_button", 246, 1),
    ("segmented_control", 247, 1),
    ("shortcut_editor", 248, 1),
    ("signature_pad", 249, 2),
    ("slider", 251, 4),
    ("snackbar", 255, 2),
    ("spin_box", 257, 2),
    ("splash_screen", 259, 2),
    ("split_button", 261, 3),
    ("splitter", 264, 2),
    ("stacked_widget", 266, 1),
    ("status_bar", 267, 1),
    ("stepper", 268, 1),
    ("swipe_to_dismiss", 269, 1),
    ("switch", 270, 1),
    ("tab_bar", 271, 3),
    ("tab_view", 274, 1),
    ("tab_widget", 275, 3),
    ("table", 278, 2),
    ("table_widget", 280, 2),
    ("tag_input", 282, 1),
    ("terminal_view", 283, 1),
    ("text_area", 284, 1),
    ("text_edit", 285, 1),
    ("time_edit", 286, 2),
    ("timeline_widget", 288, 1),
    ("toast", 289, 1),
    ("toast_stack", 290, 2),
    ("toggle_button", 292, 5),
    ("tool_bar", 297, 4),
    ("tool_box", 301, 1),
    ("tool_button", 302, 3),
    ("tree_table", 305, 2),
    ("tree_view", 307, 2),
    ("video_player", 309, 4),
    ("virtual_list", 313, 2),
    ("virtual_table", 315, 1),
    ("volume_chart", 316, 2),
    ("web_engine_view", 318, 11),
    ("window", 329, 1),
    ("wizard_dialog", 330, 3),
];
