#!/usr/bin/env python3
"""Every declared event payload must equal the real Rust type of the signal behind it.

# Why this gate exists

BLUE19 rule #95 makes `WidgetCapability.events` carry a payload kind, so a designer can offer a
wire whose value type is known and JSON can express a mapping. That declaration is only worth
having if it cannot be wrong: a capability that says `value_changed` carries a `Bool` while the
signal is `Signal1<i32>` produces a panel that lies, and a wire that type-checks and then fails.

The table (`src/widget/capability/event_payloads.rs`) is generated by
`tools/derive_event_payloads.py`, and this gate is the second, independent reader of the same
facts:

  * it re-derives the payload of every published event from the **signal declarations**;
  * it reads what the table actually declares (by parsing the generated `EventSchema` rows);
  * it fails when the two disagree, naming the control, the event, and both answers.

An earlier revision compared the table against the generator's own in-memory output, which is a
tautology: any bug in the generator appeared on both sides. Parsing the generated file and
re-deriving from the signals keeps the two paths genuinely separate — which is also why
`--inject` exists: it mutates the parsed table and requires the comparison to notice.

It also checks the two things the table can be wrong about *besides* the payload:

  * **coverage** — every name the census publishes has a row, and no row names an unpublished
    event. A table that quietly dropped a name would withdraw a public name silently.
  * **shape agreement** — the declared shape must be the shape the Rust type has (`Vec<T>` is not
    a scalar, `(usize, usize)` is not a single `UInt`).

Run from the repo root. `--inject <control>.<event>` declares a deliberately wrong payload for one
row and requires the gate to fail, which is the reverse-injection check BLUE19's DoD-T-1 asks for.
"""

from __future__ import annotations

import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools"))

import derive_event_payloads as derive  # noqa: E402  (path set up above)

TABLE = REPO / "src/widget/capability/event_payloads.rs"

# One generated row: `EventSchema { name: "x", payload: Some(K::Int), shape: Some(S::Scalar) },`
ROW_RE = re.compile(
    r"EventSchema \{\s*name: \"([a-z0-9_]+)\",\s*payload: (None|Some\(K::(\w+)\)),\s*"
    r"shape: (None|Some\(S::(\w+)\)),?\s*\}"
)
# The `(control, start, count)` spans, which is what says *which* control a row belongs to.
START_RE = re.compile(r'\("([a-z0-9_]+)", (\d+), (\d+)\)')


def canonical(value: str) -> str:
    """One spelling per state, so the two sides can be compared directly.

    The derivation reports Rust path segments (`K::Int`, `S::Scalar`) because it feeds a source
    file; the table stores the variant name alone (`Int`, `Scalar`); and "absent" is spelled `None`
    on one side and `-` on the other. Normalising in one place keeps the comparison from being a
    string-formatting test.
    """
    if value is None or value in ("None", "-"):
        return "-"
    return value.rsplit("::", 1)[-1]


def read_table() -> tuple[list[tuple[str, str, str]], list[tuple[str, int, int]]]:
    """The generated rows as `(name, kind, shape)` and the control spans."""
    text = TABLE.read_text()
    rows = [
        (match.group(1), canonical(match.group(3)), canonical(match.group(5)))
        for match in ROW_RE.finditer(text)
    ]
    spans = [
        (match.group(1), int(match.group(2)), int(match.group(3)))
        for match in START_RE.finditer(text)
    ]
    return rows, spans


def table_by_control() -> dict[str, list[tuple[str, str, str]]]:
    """control -> its rows, re-assembled from the table's own index.

    Reading the index rather than assuming adjacency is deliberate: if the spans and the row order
    ever disagreed, the payloads would be attributed to the wrong controls and every row would
    still look individually plausible.
    """
    rows, spans = read_table()
    by_control: dict[str, list[tuple[str, str, str]]] = {}
    for control, start, count in spans:
        by_control[control] = rows[start : start + count]
    return by_control


def delivery_failures(inject: str | None = None) -> list[str]:
    """Arms whose closure delivers a carrier their declared payload kind does not use.

    # What this catches that the type check cannot

    The payload table says what a subscriber will *receive*; the signal type says what the control
    *emits*. `event_signal_dyn` sits between them and decides the carrier, so it is the one place
    where the two can silently disagree — a `Signal1<String>` resolved with `|_| Null` satisfies
    both the type check and the name check and still delivers nothing.

    # Why the comparison is per control, read from the arm source

    The arm text is read from the file `check_event_signal_dyn.py` records for the control, so the
    two gates agree on where a control lives. A control with no arm at all is not this gate's
    business — the wiring gate owns that — so it is skipped rather than double-reported.
    """
    # The carrier each declared kind travels as. `K::UInt` travels as `CapabilityValue::UInt`, not
    # `Int`: the enum has a variant for it precisely so a count or index can be relied on never to be
    # negative, and the property side already uses it for `PropertyValueKind::UInt`. Converting an
    # unsigned payload with `*v as i64` throws away that guarantee (and is lossy above `i64::MAX`),
    # which is exactly the mismatch this table is here to stop.
    #
    # A tuple or list payload has no single scalar, and the conversion for it is the debug spelling,
    # which arrives as `String`; those rows are accepted for either their own carrier or `String`.
    carrier = {
        "UInt": "UInt",
        "Int": "Int",
        "Float": "Float",
        "Bool": "Bool",
        "String": "String",
        "Color": "String",
        "Rect": "String",
    }
    composite_shapes = {"Tuple2", "Tuple3", "Tuple4", "Mixed", "ListScalar", "OptionalTuple2"}
    shape_by_key = {
        (control, name): shape for control, rows in table_by_control().items() for name, _, shape in rows
    }

    try:
        import check_event_signal_dyn as wiring  # type: ignore[import-not-found]
    except ImportError:  # pragma: no cover - the module is a sibling script
        import importlib.util

        spec = importlib.util.spec_from_file_location(
            "check_event_signal_dyn", REPO / "tools/check_event_signal_dyn.py"
        )
        wiring = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(wiring)

    failures: list[str] = []
    inject_control, _, inject_event = (inject or "").partition(".")
    if inject and inject_control not in wiring.CONVERTED:
        return [f"--inject-delivery={inject}: `{inject_control}` is not a converted control"]
    injected = False
    for control, relative in sorted(wiring.CONVERTED.items()):
        path = REPO / relative
        if not path.exists():
            continue
        source = path.read_text()
        region = wiring._struct_impl_body(source, wiring.STRUCT_IMPL.get(control, ""))
        if region is None:
            continue
        for match in re.finditer(
            r'"([a-z0-9_]+)"\s*=>\s*\{?\s*Some\(EventSignalRef::(unit|mapped)\(', region
        ):
            name, constructor = match.group(1), match.group(2)
            row = next(
                ((k, s) for n, k, s in table_by_control().get(control, []) if n == name), None
            )
            if row is None:
                continue
            kind, shape = row
            if kind == "-":
                want = "Null"
                want_alt = "Null"
            else:
                want = carrier.get(kind, "String")
                if shape in composite_shapes:
                    # A composite payload must arrive as a structured carrier, not its debug spelling.
                    # The old rule accepted `String` here, which let a tuple payload ship as
                    # `"(25.0, 75.0)"` — a value a subscriber could not read as numbers, which is the
                    # exact asymmetry BLUE19 #95 forbids. A `Rect`-kind composite may arrive as a
                    # `Rect`; every other composite arrives as a `Tuple`.
                    want = "Rect" if kind == "Rect" else "Tuple"
                    want_alt = want
                else:
                    want_alt = want
            if constructor == "unit":
                produced = "Null"
            else:
                produced = _closure_carrier(region, match.end())
            if (
                inject
                and control == inject_control
                and name == inject_event
                and constructor == "mapped"
            ):
                # Pretend the arm delivers the wrong carrier: whichever variant it currently
                # produces, report a different one. A no-op injection (an arm that already
                # delivers `Null`) must still be observable, so `Null` is never chosen as the lie.
                produced = "Bool" if produced != "Bool" else "String"
                injected = True
            acceptable = {want} if kind == "-" or want_alt == want else {want, want_alt}
            if produced not in acceptable:
                failures.append(
                    f"{control}.{name}: declares payload={kind}/shape={shape}, so a subscriber "
                    f"expects {sorted(acceptable)}, but the arm delivers `{produced}`"
                )

    if inject and not injected:
        failures.append(
            f"--inject-delivery={inject}: no `mapped` arm was found to corrupt, so the injection "
            "proved nothing"
        )

    return failures


def _closure_carrier(region: str, from_index: int) -> str:
    """The `CapabilityValue` variant the `mapped` closure at `from_index` produces.

    The closure body is located by the **arm's own** delimiters rather than by searching for the
    next `|v| {`: an arm written on one line (`|v| CapabilityValue::Int(*v as i64)`) has no braced
    body at all, and a search for one would run past it into a *later* arm and report that arm's
    carrier as this one's. The body therefore ends at the first `)` that closes the `mapped(`
    call, which is found by counting parens from the `mapped(` the caller matched.
    """
    body = region[from_index:]
    depth = 1  # the `mapped(` call's own open paren
    end = 0
    for end, ch in enumerate(body):
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                break
    body = body[:end]
    for variant in ("UInt", "Int", "Float", "Bool", "String", "Null", "Tuple", "Rect"):
        if f"CapabilityValue::{variant}" in body:
            return variant

    return "?"


def main() -> int:
    inject = None
    inject_delivery = None
    for argument in sys.argv[1:]:
        if argument.startswith("--inject="):
            inject = argument.split("=", 1)[1]
        elif argument.startswith("--inject-delivery="):
            inject_delivery = argument.split("=", 1)[1]
    published = derive.read_census()
    declared = table_by_control()
    failures: list[str] = []

    if inject is not None:
        control, _, event = inject.partition(".")
        rows = declared.get(control)
        if not rows:
            print(f"❌ --inject: `{control}` has no rows in {TABLE.name}")
            return 1
        for index, (name, kind, shape) in enumerate(rows):
            if name == event:
                # A payload the signal demonstrably does not have: the gate must reject it, so a
                # comparison that only ever prints "ok" cannot pass this mode.
                rows[index] = (name, "Bool" if kind != "Bool" else "String", "Scalar")
                break
        else:
            print(f"❌ --inject: `{control}` does not declare `{event}`")
            return 1

    # ── Coverage: the table and the census must name the same events ──
    expected = {(control, name) for control, names in published.items() for name in names}
    actual = {(control, name) for control, rows in declared.items() for name, _, _ in rows}
    for control, name in sorted(expected - actual):
        failures.append(f"{control}: `{name}` is published but has no row in {TABLE.name}")
    for control, name in sorted(actual - expected):
        failures.append(f"{control}: `{name}` has a row but is not in the census")

    # ── Payloads: re-derive from the signals and compare ──
    fields, accessors = derive.collect_signals()
    aliases = derive.collect_type_aliases()
    checked = 0
    for control in sorted(published):
        fallback = derive.pascal_case(control)
        struct = derive.resolve_owner(control, aliases)
        for name, kind, shape in declared.get(control, []):
            declaration = derive.resolve_declaration(struct, name, fields, accessors, fallback)
            if declaration is None:
                failures.append(f"{control}.{name}: no signal named `{name}` on `{struct}`")
                continue
            payload = derive.payload_of(declaration)
            if payload is None:
                failures.append(f"{control}.{name}: `{declaration}` has no payload argument")
                continue
            try:
                want_kind, want_shape = derive.classify(payload)
            except derive.Unsupported as reason:
                failures.append(f"{control}.{name}: {reason}")
                continue
            # `classify` returns Rust path segments; the table stores the variant name only.
            want_kind = canonical(want_kind)
            want_shape = canonical(want_shape)
            checked += 1
            if kind != want_kind or shape != want_shape:
                failures.append(
                    f"{control}.{name}: declares payload={kind}/shape={shape} while the signal "
                    f"`{declaration}` has payload={want_kind}/shape={want_shape}"
                )

    print(f"published events checked: {checked}")
    print(f"controls covered: {len(published)}")

    # ── Delivery: the carrier `event_signal_dyn` produces must match the declared kind ──
    #
    # A declared kind is a promise about the `CapabilityValue` a subscriber receives. The signal
    # type is one half of that promise (checked above); the `mapped` closure in
    # `Widget::event_signal_dyn` is the other, and until this check existed nothing compared the
    # two: a control could declare `K::String`, resolve the name, and deliver `Null` — a wire that
    # type-checks as text and arrives empty. That is the shape BLUE19 #95 rules out, and it is
    # exactly what a bulk conversion produces when it maps `Signal1<String>` with `|_| Null`.
    #
    # The comparison is over the *carrier variant*, not the Rust type: `K::UInt` and `K::Int` both
    # travel as `CapabilityValue::Int`, and a tuple or list payload travels as the debug spelling
    # because a hub name has no arity. Only the kind's own carrier is required.
    delivery = delivery_failures(inject=inject_delivery)
    if delivery:
        print()
        print(f"❌ {len(delivery)} `event_signal_dyn` arm(s) deliver a carrier their row does not declare:")
        for failure in delivery:
            print(f"   {failure}")
        print()
        print("   Fix the arm's closure, or correct the declared payload.")
        return 1

    print(f"controls wired: {sum(1 for c in declared if declared[c])}")
    shapes: dict[str, int] = {}
    for rows in declared.values():
        for _, _, shape in rows:
            shapes[shape] = shapes.get(shape, 0) + 1
    print("declared shapes: " + ", ".join(f"{name}={count}" for name, count in sorted(shapes.items())))

    if failures:
        print()
        print(f"❌ {len(failures)} declared payload(s) disagree with the signal behind them:")
        for failure in failures:
            print(f"   {failure}")
        print()
        print("   Regenerate with `python3 tools/derive_event_payloads.py`, or fix the signal.")
        return 1

    if inject is not None:
        # Reached only when an injection did **not** produce a failure, which means the comparison
        # is not actually comparing. Failing here is the point of the mode.
        print(f"❌ --inject={inject} did not produce a failure, so this gate is not checking")
        return 1

    print()
    print("✅ every declared event payload matches the Rust type of its signal")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
