#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2026 Mike Li/Mikewolfli/Wei Li(mikewolfli@163.com)
# SPDX-License-Identifier: MIT
#
# ============================================================================
# check_svg_snapshots.sh — BLUE20 layer 3 (SVG 全量快照再生门禁)
# ============================================================================
# The rule this guards (BLUE20 #106):
#
#   **A snapshot that is not regenerated by a gate is a picture someone looked at
#   once, not an artifact that catches a regression.**
#
# Why the snapshots are committed and re-generated here
# -----------------------------------------------------
# Layers 1 and 2 are machine judgements; they cannot see "this control looks wrong".
# The 376 SVGs under `snapshots/svg/` are the human-reviewable half — 188 controls in
# two appearances, one file each, diffable. That value depends entirely on the files
# being *current*: if a control's drawing changes and the snapshot does not, the next
# reviewer approves a picture of something that no longer exists.
#
# So this gate regenerates the whole set into a scratch directory and requires a
# byte-for-byte match. It is the same shape as `check_generated_sources.sh` and
# `check_abi.sh`: the generator is the source of truth, the committed file is a
# build artifact that must equal its producer's output.
#
# What it asserts
# ---------------
#   [1] the count is 188 dark + 188 light = 376, named by canonical name
#   [2] every file is non-empty and contains at least one drawing element
#   [3] regeneration matches the committed files byte for byte
#   [4] the two appearances actually differ for every control
#
# Step [4] is the one that would have caught the defect this layer first shipped
# with: before `theme::apply_theme_to_widget` existed, every `.svg` and its
# `.light.svg` were byte-identical apart from a comment — the snapshots existed,
# listed correctly, and showed nothing about the theme.
#
# Exit 0 = snapshots current and complete. Exit 1 = a finding.
# ============================================================================

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

. "$ROOT_DIR/tools/lib_timeout.sh"
. "$ROOT_DIR/tools/lib_python.sh"

STEP_BUDGET="${RW_GATE_TIMEOUT:-900}"
SNAPSHOT_DIR="snapshots/svg"
# A scratch tree, never in the repo: a failure must not leave the working tree dirty for
# the next gate, and a partial regeneration must not be mistaken for a good one.
SCRATCH="$(mktemp -d)"
trap 'rm -rf "$SCRATCH"' EXIT

echo "[1/4] capture the committed state, then regenerate into a scratch tree"
# The committed files are hashed BEFORE anything regenerates. Comparing `git diff` AFTER
# the exporter has run in place cannot detect a changed snapshot: the exporter overwrites
# the change and the tree looks clean again. That made the first version of this gate pass
# when a committed byte was edited by hand — the exact silent-pass defect (BLUE20 #107,
# and the round-58 §3.2.1 "window at (0,0)" false pass). Hashing first is what makes the
# comparison meaningful.
BEFORE="$SCRATCH/before.sha"
if command -v sha256sum >/dev/null 2>&1; then
    find "$SNAPSHOT_DIR" -maxdepth 1 -name '*.svg' -print0 | sort -z | xargs -0 sha256sum > "$BEFORE" 2>/dev/null || true
else
    # Windows hosts frequently lack `sha256sum`; `shasum` is the common fallback and
    # `certutil` is the last resort. A gate that cannot hash must say so rather than
    # silently compare nothing.
    (cd "$SNAPSHOT_DIR" && find . -maxdepth 1 -name '*.svg' | sort | xargs shasum -a 256) > "$BEFORE" 2>/dev/null || {
        echo "  FAIL  no SHA-256 tool available, so the snapshot comparison cannot run"
        exit 1
    }
fi
if [[ ! -s "$BEFORE" ]]; then
    echo "  FAIL  hashing the committed snapshots produced nothing"
    exit 1
fi

echo "[2/4] regenerate every snapshot in place"
if ! rw_run_bounded "$STEP_BUDGET" cargo run \
    --no-default-features --features desktop \
    --example export_control_svgs > "$SCRATCH/export.log" 2>&1; then
    echo "  FAIL  the SVG exporter did not run"
    sed -n '1,60p' "$SCRATCH/export.log"
    exit 1
fi
grep -E '^(wrote|checked)' "$SCRATCH/export.log" || true

AFTER="$SCRATCH/after.sha"
if command -v sha256sum >/dev/null 2>&1; then
    find "$SNAPSHOT_DIR" -maxdepth 1 -name '*.svg' -print0 | sort -z | xargs -0 sha256sum > "$AFTER" 2>/dev/null || true
else
    (cd "$SNAPSHOT_DIR" && find . -maxdepth 1 -name '*.svg' | sort | xargs shasum -a 256) > "$AFTER" 2>/dev/null || true
fi

if ! diff -q "$BEFORE" "$AFTER" > /dev/null; then
    echo "  FAIL  the committed snapshots differ from a fresh export (byte-for-byte):"
    diff "$BEFORE" "$AFTER" | sed -n '1,40p'
    echo "  Regenerate with:"
    echo "    cargo run --no-default-features --features desktop --example export_control_svgs"
    exit 1
fi
echo "  PASS  regeneration reproduces every committed byte"

echo "[3/4] count, naming and drawing content"
CONTROLS="$("$PYTHON" -c '
import re, pathlib
src = pathlib.Path("src/widget/capability/properties.rs").read_text(encoding="utf-8")
print(len(re.findall(r"canonical_name:\s*\x22", src)))
')"
COMMITTED="$(find "$SNAPSHOT_DIR" -maxdepth 1 -name '*.svg' | wc -l)"
if [[ "$COMMITTED" -ne $((CONTROLS * 2)) ]]; then
    echo "  FAIL  expected $((CONTROLS * 2)) committed SVGs ($CONTROLS controls x 2 appearances), found $COMMITTED"
    exit 1
fi
echo "  PASS  $CONTROLS controls x 2 appearances = $COMMITTED files"

echo "[3b/4] every file has a drawing element, not just an svg skeleton"
EMPTY="$("$PYTHON" - <<'PY'
import pathlib

DRAWING = ("<rect", "<circle", "<line", "<path", "<polygon", "<polyline", "<text", "<ellipse")
bad = []
for path in sorted(pathlib.Path("snapshots/svg").glob("*.svg")):
    text = path.read_text(encoding="utf-8")
    if "<svg" not in text:
        bad.append(f"{path}: no <svg> element")
    elif not any(tag in text for tag in DRAWING):
        bad.append(f"{path}: an empty skeleton with no drawing element")
if bad:
    print("\n".join(bad))
PY
)"
if [[ -n "$EMPTY" ]]; then
    echo "  FAIL  these snapshots contain no drawing:"
    printf '%s\n' "$EMPTY"
    exit 1
fi
echo "  PASS  every snapshot contains at least one drawing element"

echo "[4/4] the appearances differ for every control, or the control is recorded as exempt"
SAME="$("$PYTHON" - <<'PY'
# A control whose two appearances render identically is theme-blind. That is the P3
# judgement `tools/check_control_rendering.sh` already makes, with the same two exemption
# tables (data colours and recorded known-blind controls), so this step applies the SAME
# tables rather than inventing a third policy: an unrecorded control that renders the
# same in both files must be a *new* regression, and a *recorded* one must not be
# reported twice or the two gates would disagree about the same fact.
#
# The reason this is repeated here at all is that it is a different *measurement* of the
# same property: P3 compares dominant pixel colours after a real render, this compares the
# emitted SVG vector stream. The exporter bug this layer first shipped with (§ the header)
# was invisible to P3 — the census applies the theme itself, so it saw the colours change
# while the snapshots did not.
import pathlib

# The two exemption tables, read the same way the census test reads them: the first
# whitespace-separated field of each non-comment line.
def exempted(path):
    names = set()
    p = pathlib.Path(path)
    if not p.exists():
        return names
    for line in p.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        names.add(stripped.split()[0])
    return names

EXEMPT = exempted("tools/control_color_exemptions.txt") | exempted(
    "tools/control_surface_coincidence_exemptions.txt"
)
# The recorded known-blind list lives in the census test, because it is a to-do list that
# must shrink as the controls are fixed. Parsed rather than duplicated so the two cannot
# disagree about what is still outstanding.
import re
census_src = pathlib.Path("tests/control_rendering_census_test.rs").read_text(encoding="utf-8")
match = re.search(r"const KNOWN_THEME_BLIND: &\[&str\] = &\[(.*?)\];", census_src, re.S)
KNOWN = set(re.findall(r'"([a-z0-9_]+)"', match.group(1))) if match else set()

# An empty exemption set would silently pass everything, which is the vacuous-gate
# failure mode: refuse to report success on a table that did not load.
if not EXEMPT:
    raise SystemExit("the exemption table could not be read, so this step cannot judge")

same = []
for path in sorted(pathlib.Path("snapshots/svg").glob("*.svg")):
    if path.name.endswith(".light.svg"):
        continue
    name = path.name[: -len(".svg")]
    light = path.with_name(path.name[: -len(".svg")] + ".light.svg")
    if not light.exists():
        same.append(f"{name}: no light companion")
        continue
    # The provenance comment names the appearance, so compare the drawing only. Comparing
    # whole files would report "differs" for every control, comment and all.
    def drawing(p):
        return [line for line in p.read_text(encoding="utf-8").splitlines()
                if not line.lstrip().startswith("<!--")]
    if drawing(path) == drawing(light) and name not in EXEMPT and name not in KNOWN:
        same.append(f"{name}: renders identically in light and dark, and is not exempt or recorded")
if same:
    print("\n".join(same))
PY
)"
if [[ -n "$SAME" ]]; then
    echo "  FAIL  these controls do not respond to the theme, so their snapshot pair proves nothing:"
    printf '%s\n' "$SAME"
    echo "  If a control is theme-blind on purpose, register it with its reason in"
    echo "  tools/control_color_exemptions.txt; if it is a defect, fix the control."
    exit 1
fi

echo ""
echo "check_svg_snapshots: checked=$CONTROLS skipped=0 failed=0 (each with a dark and a light snapshot)"
