#!/usr/bin/env python3
"""Every declared event payload must equal the real Rust type of the signal behind it.

# Why this gate exists

BLUE19 rule #95 makes `WidgetCapability.events` carry a payload kind, so a designer can offer a
wire whose value type is known and JSON can express a mapping. That declaration is only worth
having if it cannot be wrong: a capability that says `value_changed` carries a `Bool` while the
signal is `Signal1<i32>` produces a panel that lies, and a wire that type-checks and then fails.

The table (`src/widget/capability/event_payloads.rs`) is generated by
`tools/derive_event_payloads.py`, and this gate is the second, independent reader of the same
facts:

  * it re-derives the payload of every published event from the **signal declarations**;
  * it reads what the table actually declares (by parsing the generated `EventSchema` rows);
  * it fails when the two disagree, naming the control, the event, and both answers.

An earlier revision compared the table against the generator's own in-memory output, which is a
tautology: any bug in the generator appeared on both sides. Parsing the generated file and
re-deriving from the signals keeps the two paths genuinely separate — which is also why
`--inject` exists: it mutates the parsed table and requires the comparison to notice.

It also checks the two things the table can be wrong about *besides* the payload:

  * **coverage** — every name the census publishes has a row, and no row names an unpublished
    event. A table that quietly dropped a name would withdraw a public name silently.
  * **shape agreement** — the declared shape must be the shape the Rust type has (`Vec<T>` is not
    a scalar, `(usize, usize)` is not a single `UInt`).

Run from the repo root. `--inject <control>.<event>` declares a deliberately wrong payload for one
row and requires the gate to fail, which is the reverse-injection check BLUE19's DoD-T-1 asks for.
"""

from __future__ import annotations

import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools"))

import derive_event_payloads as derive  # noqa: E402  (path set up above)

TABLE = REPO / "src/widget/capability/event_payloads.rs"

# One generated row: `EventSchema { name: "x", payload: Some(K::Int), shape: Some(S::Scalar) },`
ROW_RE = re.compile(
    r"EventSchema \{\s*name: \"([a-z0-9_]+)\",\s*payload: (None|Some\(K::(\w+)\)),\s*"
    r"shape: (None|Some\(S::(\w+)\)),?\s*\}"
)
# The `(control, start, count)` spans, which is what says *which* control a row belongs to.
START_RE = re.compile(r'\("([a-z0-9_]+)", (\d+), (\d+)\)')


def canonical(value: str) -> str:
    """One spelling per state, so the two sides can be compared directly.

    The derivation reports Rust path segments (`K::Int`, `S::Scalar`) because it feeds a source
    file; the table stores the variant name alone (`Int`, `Scalar`); and "absent" is spelled `None`
    on one side and `-` on the other. Normalising in one place keeps the comparison from being a
    string-formatting test.
    """
    if value is None or value in ("None", "-"):
        return "-"
    return value.rsplit("::", 1)[-1]


def read_table() -> tuple[list[tuple[str, str, str]], list[tuple[str, int, int]]]:
    """The generated rows as `(name, kind, shape)` and the control spans."""
    text = TABLE.read_text()
    rows = [
        (match.group(1), canonical(match.group(3)), canonical(match.group(5)))
        for match in ROW_RE.finditer(text)
    ]
    spans = [
        (match.group(1), int(match.group(2)), int(match.group(3)))
        for match in START_RE.finditer(text)
    ]
    return rows, spans


def table_by_control() -> dict[str, list[tuple[str, str, str]]]:
    """control -> its rows, re-assembled from the table's own index.

    Reading the index rather than assuming adjacency is deliberate: if the spans and the row order
    ever disagreed, the payloads would be attributed to the wrong controls and every row would
    still look individually plausible.
    """
    rows, spans = read_table()
    by_control: dict[str, list[tuple[str, str, str]]] = {}
    for control, start, count in spans:
        by_control[control] = rows[start : start + count]
    return by_control


def main() -> int:
    inject = None
    for argument in sys.argv[1:]:
        if argument.startswith("--inject="):
            inject = argument.split("=", 1)[1]
    published = derive.read_census()
    declared = table_by_control()
    failures: list[str] = []

    if inject is not None:
        control, _, event = inject.partition(".")
        rows = declared.get(control)
        if not rows:
            print(f"❌ --inject: `{control}` has no rows in {TABLE.name}")
            return 1
        for index, (name, kind, shape) in enumerate(rows):
            if name == event:
                # A payload the signal demonstrably does not have: the gate must reject it, so a
                # comparison that only ever prints "ok" cannot pass this mode.
                rows[index] = (name, "Bool" if kind != "Bool" else "String", "Scalar")
                break
        else:
            print(f"❌ --inject: `{control}` does not declare `{event}`")
            return 1

    # ── Coverage: the table and the census must name the same events ──
    expected = {(control, name) for control, names in published.items() for name in names}
    actual = {(control, name) for control, rows in declared.items() for name, _, _ in rows}
    for control, name in sorted(expected - actual):
        failures.append(f"{control}: `{name}` is published but has no row in {TABLE.name}")
    for control, name in sorted(actual - expected):
        failures.append(f"{control}: `{name}` has a row but is not in the census")

    # ── Payloads: re-derive from the signals and compare ──
    fields, accessors = derive.collect_signals()
    aliases = derive.collect_type_aliases()
    checked = 0
    for control in sorted(published):
        fallback = derive.pascal_case(control)
        struct = derive.resolve_owner(control, aliases)
        for name, kind, shape in declared.get(control, []):
            declaration = derive.resolve_declaration(struct, name, fields, accessors, fallback)
            if declaration is None:
                failures.append(f"{control}.{name}: no signal named `{name}` on `{struct}`")
                continue
            payload = derive.payload_of(declaration)
            if payload is None:
                failures.append(f"{control}.{name}: `{declaration}` has no payload argument")
                continue
            try:
                want_kind, want_shape = derive.classify(payload)
            except derive.Unsupported as reason:
                failures.append(f"{control}.{name}: {reason}")
                continue
            # `classify` returns Rust path segments; the table stores the variant name only.
            want_kind = canonical(want_kind)
            want_shape = canonical(want_shape)
            checked += 1
            if kind != want_kind or shape != want_shape:
                failures.append(
                    f"{control}.{name}: declares payload={kind}/shape={shape} while the signal "
                    f"`{declaration}` has payload={want_kind}/shape={want_shape}"
                )

    print(f"published events checked: {checked}")
    print(f"controls covered: {len(published)}")
    shapes: dict[str, int] = {}
    for rows in declared.values():
        for _, _, shape in rows:
            shapes[shape] = shapes.get(shape, 0) + 1
    print("declared shapes: " + ", ".join(f"{name}={count}" for name, count in sorted(shapes.items())))

    if failures:
        print()
        print(f"❌ {len(failures)} declared payload(s) disagree with the signal behind them:")
        for failure in failures:
            print(f"   {failure}")
        print()
        print("   Regenerate with `python3 tools/derive_event_payloads.py`, or fix the signal.")
        return 1

    if inject is not None:
        # Reached only when an injection did **not** produce a failure, which means the comparison
        # is not actually comparing. Failing here is the point of the mode.
        print(f"❌ --inject={inject} did not produce a failure, so this gate is not checking")
        return 1

    print()
    print("✅ every declared event payload matches the Rust type of its signal")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
