#!/usr/bin/env bash
# ============================================================================
# check_view_platform_gate.sh — BLUE18 rules #92 / #94
# ============================================================================
# The architectural rule this guards:
#
#   The declarative-retained view layer (`src/view/`) is a heavyweight optional
#   part. It is compiled for `desktop` / `tablet` / `mobile`, and is ABSENT for
#   `mini` / `embedded`, which are retained-only (imperative `add_child`).
#
# Why this gate exists at all
# ---------------------------
# The gate expression in `src/lib.rs` was already correct before this script
# existed: it is the same `all(any(desktop, tablet, mobile), widgets_unstripped)`
# that `crate::json` uses. But nothing ASKED the question, so a harmless-looking
# refactor — dropping `widgets_unstripped`, or narrowing to `feature = "desktop"`
# — would silently compile the declarative layer into `mini`/`embedded`. That
# regression is invisible on a desktop build: nothing fails, the tests stay
# green, and only an embedded target pays for a layer it has no caller for.
#
# The criterion is executable, not a grep
# ---------------------------------------
# Grepping a build log for `src/view` would also match a path inside an unrelated
# diagnostic, and grepping `src/lib.rs` for the `cfg` text only proves the text is
# present, not that it has the intended effect. Instead this script compiles a
# tiny probe that NAMES a symbol exported from the module:
#
#     rust_widgets::view::VIEW_GATE_PROBE
#
# The probe resolves exactly when the module is part of the compilation unit, and
# fails to resolve when it is not — the same name resolution a real caller
# performs. So the gate cannot be satisfied by anything short of the module
# actually being compiled, or actually being absent.
#
# How the probe is built
# ----------------------
# As a cargo *test* target of this crate (`--test`), which means the crate's own
# feature resolution applies with no copy of the feature table. `--test` is used
# rather than `--example` because examples are auto-discovered from `examples/`,
# while a test file can be named explicitly by path from `Cargo.toml`. The probe
# is written to a stable path and passed with `--test <name>`; see the
# `[[test]]` entry in `Cargo.toml`. `--no-run` type-checks without executing.
#
# Exit 0 = the gate holds in every profile. Exit 1 = a regression was found.
# ============================================================================

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

ERRORS=0

# ---------------------------------------------------------------------------
# The committed probe (`tools/view_platform_gate_probe.rs`) `cfg`-gates its import
# so that a normal `--all-targets` build stays green on every profile. This gate
# needs the opposite: an import that is forced unconditional, so that a build
# failing IS the assertion that the module is absent.
#
# It therefore saves the committed file, writes the forced copy, runs the six
# profiles, and restores the original on exit. The save/restore is what keeps a
# crashed run from leaving a file that breaks `--all-targets` on mini/embedded.
# ---------------------------------------------------------------------------
PROBE="tools/view_platform_gate_probe.rs"
PROBE_BAK="$(mktemp)"

cleanup() {
  if [[ -f "$PROBE_BAK" ]]; then
    cp "$PROBE_BAK" "$PROBE"
    rm -f "$PROBE_BAK"
  fi
}
trap cleanup EXIT

cp "$PROBE" "$PROBE_BAK"

cat > "$PROBE" <<'PROBE'
// SPDX-FileCopyrightText: Copyright (c) 2026 Mike Li/Mikewolfli/Wei Li(mikewolfli@163.com)
// SPDX-License-Identifier: MIT

//! Generated by `tools/check_view_platform_gate.sh`; the committed file is restored
//! when the gate exits. The import is forced unconditional on purpose: resolving it
//! is the assertion that `crate::view` is compiled into this profile.

#![allow(unused_imports)]
#![allow(dead_code)]

use rust_widgets::view::VIEW_GATE_PROBE;

#[test]
fn view_gate_probe_resolves() {
    assert!(!VIEW_GATE_PROBE.is_empty());
}
PROBE

# ---------------------------------------------------------------------------
# Type-check the probe under one feature set and assert the outcome.
#
# `--no-run` compiles and links the test binary without executing it, which is
# what makes this a *compile-time* criterion. The outcome is read from the exit
# status, and the failure text is captured so a failure can quote the reason
# rather than only reporting a status code.
# ---------------------------------------------------------------------------
check_profile() {
  local label="$1"
  local expect="$2"
  shift 2

  local out status
  set +e
  out="$(cargo test --test view_platform_gate_probe --no-run "$@" 2>&1)"
  status=$?
  set -e

  case "$expect" in
    present)
      if [[ $status -eq 0 ]]; then
        echo "  ✅ $label — crate::view IS compiled (probe resolved)"
      else
        echo "  ❌ $label — crate::view must be compiled, but the probe did not resolve"
        printf '%s\n' "$out" | grep -E '^error|^ *-->' | head -6 | sed 's/^/       /'
        ERRORS=$((ERRORS + 1))
      fi
      ;;
    absent)
      if [[ $status -eq 0 ]]; then
        echo "  ❌ $label — crate::view must NOT be compiled, but the probe resolved"
        echo "       the declarative layer is in a stripped profile (rule #92)."
        echo "       check that src/lib.rs's \`pub mod view\` still carries"
        echo "       \`all(any(desktop, tablet, mobile), widgets_unstripped)\`"
        ERRORS=$((ERRORS + 1))
      elif printf '%s' "$out" | grep -qE 'VIEW_GATE_PROBE|could not find .view.|unresolved import|no .view. in'; then
        echo "  ✅ $label — crate::view is ABSENT (probe cannot resolve it)"
      else
        echo "  ❌ $label — the probe failed for a reason unrelated to the gate:"
        printf '%s\n' "$out" | grep -E '^error' | head -6 | sed 's/^/       /'
        ERRORS=$((ERRORS + 1))
      fi
      ;;
  esac
}

echo "=== [1] Device profiles must compile the declarative layer ==="
check_profile "desktop" present
check_profile "tablet" present --no-default-features --features tablet
check_profile "mobile" present --no-default-features --features mobile

echo ""
echo "=== [2] Stripped profiles must not compile it (rules #92/#93) ==="
check_profile "mini" absent --no-default-features --features mini
check_profile "embedded" absent --no-default-features --features embedded

echo ""
echo "=== [3] A build with no device profile must not compile it ==="
# `--no-default-features --features gpu` has no device profile, so `full_widgets`
# is false and the widget factory is not registered: the declarative layer would
# have nothing to mount onto. This is the case a bare
# `not(any(mini, embedded))` spelling would wrongly admit, which is why the gate
# expression tests the profile as well as the stripped pair.
check_profile "gpu-only (no device profile)" absent --no-default-features --features gpu

echo ""
echo "=== [4] The gate expression must retain its 'widgets_unstripped' term ==="
#
# WHY THIS SECOND CRITERION IS NECESSARY (measured, not assumed)
# ---------------------------------------------------------------
# On every *valid* single-profile build the two spellings
# `all(any(desktop,tablet,mobile), widgets_unstripped)` and
# `any(desktop,tablet,mobile)` behave identically:
#
#   * a device profile (desktop/tablet/mobile) is never stripped, so
#     `widgets_unstripped` is true and the `all` reduces to the `any`;
#   * `mini`/`embedded` carry no device feature, so both spellings are false.
#
# They differ ONLY on the mixed build `--features desktop,mini`, which is the
# invalid configuration BLUE18 rule #48 forbids (mutually exclusive device
# profiles). So the behavioural probes above CANNOT distinguish the two
# spellings, and a gate that only ran them would be a gate that cannot fail —
# which is the exact failure mode BLUE18 Phase E'-5 asks to rule out.
#
# This step therefore asserts the *term* is present, so a refactor that drops
# `widgets_unstripped` is caught even though no valid build would notice it. It
# is a source check, and it is honest about being one: it does not claim to prove
# runtime behaviour, because the behaviour it protects is unobservable on a valid
# build. Together with steps [1]-[3] (which prove the expression has the right
# effect where it IS observable) the two criteria cover each other's blind spot.
VIEW_GATE_LINE="$(grep -n 'pub mod view;' -B 1 src/lib.rs || true)"
if printf '%s' "$VIEW_GATE_LINE" | grep -q 'widgets_unstripped'; then
  echo "  ✅ src/lib.rs gates \`pub mod view\` on \`widgets_unstripped\`"
else
  echo "  ❌ src/lib.rs's \`pub mod view\` no longer mentions \`widgets_unstripped\`:"
  printf '%s\n' "$VIEW_GATE_LINE" | sed 's/^/       /'
  echo "       On every valid single-profile build this is undetectable (see the"
  echo "       note above), which is why it is asserted here: it is the only"
  echo "       spelling that also excludes the invalid mixed configuration."
  ERRORS=$((ERRORS + 1))
fi

# The expression must also be the multi-profile one. A `feature = \"desktop\"`
# narrowing would silently take the declarative layer away from tablet/mobile,
# which `src/lib.rs` already fixed once for `theme`.
if printf '%s' "$VIEW_GATE_LINE" | grep -qE 'feature = "tablet"' && \
   printf '%s' "$VIEW_GATE_LINE" | grep -qE 'feature = "mobile"'; then
  echo "  ✅ the gate covers all three device profiles (desktop/tablet/mobile)"
else
  echo "  ❌ the \`view\` gate does not list all three device profiles — a tablet or"
  echo "     mobile build would lose the declarative layer:"
  printf '%s\n' "$VIEW_GATE_LINE" | sed 's/^/       /'
  ERRORS=$((ERRORS + 1))
fi

echo ""
if [[ "$ERRORS" -gt 0 ]]; then
  echo "view platform gate: FAILED ($ERRORS finding(s))" >&2
  echo "" >&2
  echo "To confirm this gate can fail (BLUE18 Phase E'-5): drop" >&2
  echo "\`widgets_unstripped\` from the \`pub mod view\` gate in src/lib.rs and" >&2
  echo "re-run — step [4] must report ❌ immediately." >&2
  exit 1
fi

echo "✅ view platform gate passed: declarative layer present on"
echo "   desktop/tablet/mobile, absent on mini/embedded and on a profile-less build,"
echo "   and the gate expression retains its \`widgets_unstripped\` term."
