#!/usr/bin/env bash
# Committed generated sources must match their project documents **and** compile clean
# (BLUE19 D7-b-3).
#
# # Why this gate exists
#
# D7-b-3 decides that generated sources are **committed**, for reviewability: a generated file in the
# tree is a diff a reviewer sees in the same pull request as the project document that caused it.
# The cost of committing is that the tree can hold a **stale** file, which is why the decision is
# only safe with this gate.
#
# The hazard is specific and quiet: a designer edits `project.json`, commits the document, and forgets
# to regenerate. The tree now claims to describe a UI it does not, and nothing about the committed
# `.rs` file looks wrong — it is valid Rust that compiles. The only way to catch it is to regenerate
# and compare, which is exactly what `tools/check_abi.sh` step [2] already does for the C header. This
# is the same shape for the same reason.
#
# # What it asserts
#
#   [1] every committed artifact carries the generated marker (a file without it is not compared —
#       pointing the tool at a hand-written module must fail loudly, not report drift forever)
#   [2] regenerating reproduces the committed bytes exactly
#   [3] the committed artifacts compile with `-D warnings`
#   [4] reverse injections, one per direction:
#         (a) editing the document produces different bytes, so [2] can actually fail;
#         (b) restoring an unconditional `mut` in the generator fails [3]
#
# [4a] is not optional: a `cmp` against a file the tool just wrote passes trivially, so the gate has
# to show it would notice a real change. [4b] exists because the `-D warnings` step found the `mut`
# defect in **both** directions at once (an unneeded `mut` on a child, a missing one on the root), and
# neither showed in the fixture-based compile test — that makes it the defect class this step is for.
#
# # Exit status
#
# 0 = every committed artifact matches its document and compiles clean. 1 = drift, a missing artifact,
# or a lint failure.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

. "$ROOT_DIR/tools/lib_python.sh"
. "$ROOT_DIR/tools/lib_timeout.sh"
. "$ROOT_DIR/tools/lib_cargo_cache.sh"

# Generation is a Rust compile plus a run; the lint step is a second compile. Bounded per rule #58.
GATE_TIMEOUT="${GATE_TIMEOUT:-900}"

# The committed project. `dir:width:height` — the geometry is part of the artifact's identity, so a
# mismatch there is drift too.
PROJECT_DIR="examples/generated_project"
PROJECT_WIDTH=640
PROJECT_HEIGHT=480

# The marker the writer emits. Kept in one variable so a shell-side check cannot drift from
# `designer::artifact::GENERATED_MARKER`; step [1] also verifies it against the generated text, so a
# change on either side fails rather than silently skipping the file.
MARKER="// Generated by the rust_widgets designer. Do not edit by hand."

GENERATE() {
  local root="$1" project="$2"
  shift 2
  # **Not** through `rw_cargo_cached`.
  #
  # `designer_generate` *writes* `$root/src/generated/*.rs`. The cargo cache stores a status and the
  # two output streams and replays them without re-running the command, so a hit prints
  # "created …" while writing nothing. `REGENERATE_IN_PLACE` below does `rm -rf` first, so a cached
  # hit left the directory **deleted** and the next step failed with "commits no generated source" —
  # a false failure caused by the cache, visible only once the cache was warm.
  #
  # `$root` may also be a scratch directory outside the tree, in which case the cache key would be
  # about the *project* rather than the copy being generated. Running uncached removes both problems.
  rw_run_bounded "$GATE_TIMEOUT" cargo run --quiet \
    --no-default-features --features desktop,designer --example designer_generate -- \
    --project "$project" --root "$root" \
    --width "$PROJECT_WIDTH" --height "$PROJECT_HEIGHT" "$@"
}

fail() {
  echo "" >&2
  echo "FAIL: $1" >&2
  exit 1
}

# Regenerates the committed artifacts in place, so the tree is left in sync.
REGENERATE_IN_PLACE() {
  rm -rf "$PROJECT_DIR/src/generated"
  GENERATE "$PROJECT_DIR" "$PROJECT_DIR/project.json" > /dev/null
}

echo "=== [1/4] every committed artifact carries the generated marker ==="
# shellcheck disable=SC2207
ARTIFACTS=($(ls "$PROJECT_DIR"/src/generated/*.rs 2>/dev/null || true))
if [[ "${#ARTIFACTS[@]}" -eq 0 ]]; then
  fail "$PROJECT_DIR commits no generated source. Generate it with:
       cargo run --no-default-features --features desktop,designer --example designer_generate -- \\
         --project $PROJECT_DIR/project.json --root $PROJECT_DIR \\
         --width $PROJECT_WIDTH --height $PROJECT_HEIGHT"
fi
for artifact in "${ARTIFACTS[@]}"; do
  first_line="$(grep -m1 -v '^[[:space:]]*$' "$artifact" || true)"
  if [[ "$first_line" != "$MARKER" ]]; then
    fail "$artifact does not start with the generated marker, so it is not a file this tool wrote.
       Expected: $MARKER
       Found:    $first_line
       Either regenerate it, or move it out of src/generated/ if it is hand-written."
  fi
  echo "  OK $artifact"
done
echo "  ${#ARTIFACTS[@]} artifact(s) marked as generated"

echo ""
echo "=== [2/4] regenerating reproduces the committed bytes ==="
# A scratch copy, so a failing comparison does not leave the tree modified.
SCRATCH="$(mktemp -d)"
trap 'rm -rf "$SCRATCH"' EXIT
cp -R "$PROJECT_DIR/." "$SCRATCH/"
rm -rf "$SCRATCH/src/generated"

if ! GENERATE "$SCRATCH" "$SCRATCH/project.json" > id.gen.log 2>&1; then
  cat id.gen.log
  rm -f id.gen.log
  fail "generation failed for $PROJECT_DIR; the output above is the reason"
fi
rm -f id.gen.log

for generated in "$SCRATCH"/src/generated/*.rs; do
  name="$(basename "$generated")"
  committed="$PROJECT_DIR/src/generated/$name"
  if [[ ! -f "$committed" ]]; then
    fail "$committed is missing but the generator produces it. Regenerate with:
       cargo run --no-default-features --features desktop,designer --example designer_generate -- \\
         --project $PROJECT_DIR/project.json --root $PROJECT_DIR \\
         --width $PROJECT_WIDTH --height $PROJECT_HEIGHT"
  fi
  if ! cmp -s "$generated" "$committed"; then
    echo "" >&2
    echo "Generated source drift: $committed" >&2
    diff -u "$committed" "$generated" >&2 || true
    fail "$committed does not match $PROJECT_DIR/project.json. Regenerate with:
       cargo run --no-default-features --features desktop,designer --example designer_generate -- \\
         --project $PROJECT_DIR/project.json --root $PROJECT_DIR \\
         --width $PROJECT_WIDTH --height $PROJECT_HEIGHT"
  fi
done
echo "  regenerated output is byte-identical to the committed files"

echo ""
echo "=== [3/4] the committed artifacts compile with -D warnings ==="
if ! rw_cargo_cached "$GATE_TIMEOUT" test \
    --no-default-features --features desktop \
    --test generated_artifacts_are_lint_clean_test -- --ignored --nocapture; then
  fail "a committed generated source does not compile clean. A warning there fails a downstream
       '-D warnings' build for a reason unrelated to the project document."
fi

echo ""
echo "=== [4/4] reverse injections ==="
echo "  (a) an edited project document must produce different bytes"
INJECT_DIR="$(mktemp -d)"
cp -R "$PROJECT_DIR/." "$INJECT_DIR/"
rm -rf "$INJECT_DIR/src/generated"
"$PYTHON" - "$INJECT_DIR/project.json" <<'PY'
import json
import pathlib
import sys


def edit(node):
    """Change the first `text` in the document and report whether one was found."""
    if isinstance(node, dict):
        if "text" in node:
            node["text"] = "EDITED BY THE INJECTION"
            return True
        return any(edit(value) for value in node.values())
    if isinstance(node, list):
        return any(edit(value) for value in node)
    return False


path = pathlib.Path(sys.argv[1])
document = json.loads(path.read_text())
assert edit(document), "the fixture project must contain a `text` for the injection to change"
path.write_text(json.dumps(document, indent=2))
PY

if ! GENERATE "$INJECT_DIR" "$INJECT_DIR/project.json" > id.1.diag 2>&1; then
  cat id.1.diag
  rm -f id.1.diag
  rm -rf "$INJECT_DIR"
  fail "the injected document did not even generate, so this injection proves nothing"
fi
rm -f id.1.diag

drift_seen=0
for generated in "$INJECT_DIR"/src/generated/*.rs; do
  name="$(basename "$generated")"
  if ! cmp -s "$generated" "$PROJECT_DIR/src/generated/$name"; then
    drift_seen=1
  fi
done
rm -rf "$INJECT_DIR"
if [[ "$drift_seen" -eq 0 ]]; then
  fail "editing the project document produced no difference in the generated sources, so this gate
       cannot detect drift at all — the comparison in step [2] would pass against anything."
fi
echo "    detected: the edited document generates different bytes"

echo "  (b) a needless \`mut\` in the generator must fail the lint step"
GEN_BACKUP="$(mktemp)"
cp src/designer/generator.rs "$GEN_BACKUP"
"$PYTHON" - "$ROOT_DIR/src/designer/generator.rs" <<'PY'
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
text = path.read_text()
needle = 'body.push_str(&format!("    let {} = {expr};\\n", binding_name(path)));'
assert needle in text, "the injection point moved; update this script"
text = text.replace(needle, needle.replace("let {} =", "let mut {} ="), 1)
path.write_text(text)
PY

injection_caught=0
if REGENERATE_IN_PLACE; then
  if ! rw_cargo_cached "$GATE_TIMEOUT" test \
      --no-default-features --features desktop \
      --test generated_artifacts_are_lint_clean_test -- --ignored > id.3.diag 2>&1; then
    injection_caught=1
  fi
fi
rm -f id.3.diag

# Restore the generator **and** regenerate, so the tree is left exactly as it was found.
cp "$GEN_BACKUP" src/designer/generator.rs
rm -f "$GEN_BACKUP"
if ! REGENERATE_IN_PLACE; then
  fail "could not restore the committed artifacts after the injection. Regenerate with:
       cargo run --no-default-features --features desktop,designer --example designer_generate -- \\
         --project $PROJECT_DIR/project.json --root $PROJECT_DIR \\
         --width $PROJECT_WIDTH --height $PROJECT_HEIGHT"
fi

if [[ "$injection_caught" -eq 0 ]]; then
  fail "a needless \`mut\` in the generated output does not fail the lint step, so that step cannot
       see the defect class it exists for."
fi
echo "    detected: the lint step refuses the needless \`mut\`"

# # The tree must be left in sync
#
# An injection that mutated the committed artifacts and did not put them back would make *every later
# gate* see drift the injection created — a false failure attributed to the next thing that ran. This
# is asserted rather than assumed, because a gate that corrupts the tree on its way out is worse than
# one that fails.
if ! GENERATE "$PROJECT_DIR" "$PROJECT_DIR/project.json" --check > id.4.diag 2>&1; then
  cat id.4.diag
  rm -f id.4.diag
  fail "the working tree is left with stale generated sources after the injections"
fi
rm -f id.4.diag
echo "  tree restored and verified in sync"

echo ""
echo "generated-source checks passed."
