#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2026 Mike Li/Mikewolfli/Wei Li(mikewolfli@163.com)
# SPDX-License-Identifier: MIT
#
# ============================================================================
# check_view_platform_gate.sh — BLUE18 rules #92 / #94
# ============================================================================
# The architectural rule this guards:
#
#   The declarative-retained view layer (`src/view/`) is a heavyweight optional
#   part. It is compiled for `desktop` / `tablet` / `mobile`, and is ABSENT for
#   `mini` / `embedded`, which are retained-only (imperative `add_child`).
#
# Why this gate exists at all
# ---------------------------
# The gate expression in `src/lib.rs` was already correct before this script
# existed: it is the same `all(any(desktop, tablet, mobile), widgets_unstripped)`
# that `crate::json` uses. But nothing ASKED the question, so a harmless-looking
# refactor — dropping `widgets_unstripped`, or narrowing to `feature = "desktop"`
# — would silently compile the declarative layer into `mini`/`embedded`. That
# regression is invisible on a desktop build: nothing fails, the tests stay
# green, and only an embedded target pays for a layer it has no caller for.
#
# The criterion is executable, not a grep
# ---------------------------------------
# Grepping a build log for `src/view` would also match a path inside an unrelated
# diagnostic, and grepping `src/lib.rs` for the `cfg` text only proves the text is
# present, not that it has the intended effect. Instead this script compiles a
# tiny probe that NAMES a symbol exported from the module:
#
#     rust_widgets::view::VIEW_GATE_PROBE
#
# The probe resolves exactly when the module is part of the compilation unit, and
# fails to resolve when it is not — the same name resolution a real caller
# performs. So the gate cannot be satisfied by anything short of the module
# actually being compiled, or actually being absent.
#
# How the probe is built
# ----------------------
# As a cargo *test* target of this crate (`--test`), which means the crate's own
# feature resolution applies with no copy of the feature table. `--test` is used
# rather than `--example` because examples are auto-discovered from `examples/`,
# while a test file can be named explicitly by path from `Cargo.toml`. The probe
# is written to a stable path and passed with `--test <name>`; see the
# `[[test]]` entry in `Cargo.toml`. `--no-run` type-checks without executing.
#
# Exit 0 = the gate holds in every profile. Exit 1 = a regression was found.
# ============================================================================

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

. "$ROOT_DIR/tools/lib_timeout.sh"
. "$ROOT_DIR/tools/lib_cargo_cache.sh"

ERRORS=0

# ---------------------------------------------------------------------------
# The committed probe (`tools/view_platform_gate_probe.rs`) `cfg`-gates its import
# so that a normal `--all-targets` build stays green on every profile. This gate
# needs the opposite: an import that is forced unconditional, so that a build
# failing IS the assertion that the module is absent.
#
# It therefore saves the committed file, writes the forced copy, runs the six
# profiles, and restores the original on exit. The save/restore is what keeps a
# crashed run from leaving a file that breaks `--all-targets` on mini/embedded.
# ---------------------------------------------------------------------------
PROBE="tools/view_platform_gate_probe.rs"
PROBE_BAK="$(mktemp)"

cleanup() {
  if [[ -f "$PROBE_BAK" ]]; then
    cp "$PROBE_BAK" "$PROBE"
    rm -f "$PROBE_BAK"
  fi
}
trap cleanup EXIT

cp "$PROBE" "$PROBE_BAK"

cat > "$PROBE" <<'PROBE'
// SPDX-FileCopyrightText: Copyright (c) 2026 Mike Li/Mikewolfli/Wei Li(mikewolfli@163.com)
// SPDX-License-Identifier: MIT

//! Generated by `tools/check_view_platform_gate.sh`; the committed file is restored
//! when the gate exits. The import is forced unconditional on purpose: resolving it
//! is the assertion that `crate::view` is compiled into this profile.

#![allow(unused_imports)]
#![allow(dead_code)]

use rust_widgets::view::VIEW_GATE_PROBE;

#[test]
fn view_gate_probe_resolves() {
    assert!(!VIEW_GATE_PROBE.is_empty());
}

# ---------------------------------------------------------------------------
# Type-check the probe under one feature set and assert the outcome.
#
# `--no-run` compiles and links the test binary without executing it, which is
# what makes this a *compile-time* criterion. The outcome is read from the exit
# status, and the failure text is captured so a failure can quote the reason
# rather than only reporting a status code.
# ---------------------------------------------------------------------------
check_profile() {
  local label="$1"
  local expect="$2"
  shift 2

  local out status
  set +e
  out="$(cargo test --test view_platform_gate_probe --no-run "$@" 2>&1)"
  status=$?
  set -e

  case "$expect" in
    present)
      if [[ $status -eq 0 ]]; then
        echo "  ✅ $label — crate::view IS compiled (probe resolved)"
      else
        echo "  ❌ $label — crate::view must be compiled, but the probe did not resolve"
        printf '%s\n' "$out" | grep -E '^error|^ *-->' | head -6 | sed 's/^/       /'
        ERRORS=$((ERRORS + 1))
      fi
      ;;
    absent)
      if [[ $status -eq 0 ]]; then
        echo "  ❌ $label — crate::view must NOT be compiled, but the probe resolved"
        echo "       either the layer reached a stripped profile (rule #92), or the"
        echo "       opt-out did not take effect. Check that src/lib.rs's"
        echo "       \`pub mod view\` is gated on the single \`declarative_view\` alias."
        ERRORS=$((ERRORS + 1))
      elif printf '%s' "$out" | grep -qE 'VIEW_GATE_PROBE|could not find .view.|unresolved import|no .view. in'; then
        echo "  ✅ $label — crate::view is ABSENT (probe cannot resolve it)"
      else
        echo "  ❌ $label — the probe failed for a reason unrelated to the gate:"
        printf '%s\n' "$out" | grep -E '^error' | head -6 | sed 's/^/       /'
        ERRORS=$((ERRORS + 1))
      fi
      ;;
  esac
}

echo "=== [1] Device profiles must compile the declarative layer by default ==="
check_profile "desktop" present
check_profile "tablet" present --no-default-features --features tablet
check_profile "mobile" present --no-default-features --features mobile

echo ""
echo "=== [2] The 'no-declarative-view' opt-out must remove it from a device build ==="
# The layer is on by default for a device profile but is **opt-out**, so a caller that
# does not want its cost (a headless tool, a size-constrained device build, a program
# that only uses `add_child`) can take it out without losing the profile. Both halves
# are asserted: absent with the feature, present without it (step [1]).
check_profile "desktop + opt-out" absent --no-default-features --features desktop,no-declarative-view
check_profile "tablet + opt-out" absent --no-default-features --features tablet,no-declarative-view
check_profile "mobile + opt-out" absent --no-default-features --features mobile,no-declarative-view

echo ""
echo "=== [3] Stripped profiles must not compile it (rules #92/#93) ==="
# `mini`/`embedded` never have it, and the opt-out is not what decides that: these
# profiles lack the widget tree and allocation budget the layer needs.
check_profile "mini" absent --no-default-features --features mini
check_profile "embedded" absent --no-default-features --features embedded

echo ""
echo "=== [4] A build with no device profile must not compile it ==="
# `--no-default-features --features gpu` has no device profile, so `full_widgets`
# is false and the widget factory is not registered: the declarative layer would
# have nothing to mount onto. This is the case a bare
# `not(any(mini, embedded))` spelling would wrongly admit, which is why the gate
# expression tests the profile as well as the stripped pair.
check_profile "gpu-only (no device profile)" absent --no-default-features --features gpu

echo ""
echo "=== [5] The gate must be stated as the single 'declarative_view' alias ==="
#
# WHY THIS CRITERION EXISTS, AND WHY IT IS A SOURCE CHECK
# -------------------------------------------------------
# The layer's gate is `declarative_view`, defined once in `build.rs` as
# `device_profile && !stripped && !no-declarative-view`. Two failure modes are not
# observable from a build of any single profile:
#
#   * the alias is opened up to a stripped profile, which no valid build exercises;
#   * the tern is re-spelled by hand at the call site, so the opt-out or the
#     stripped-profile rule silently stops applying to `crate::view`.
#
# So this step asserts the term is present and that the module uses the alias rather
# than a hand-written conjunction. It is honest about being a source check: it does
# not claim to prove runtime behaviour, because the behaviour it protects is a
# property of the *feature matrix* rather than of one build.
VIEW_GATE_LINE="$(grep -n 'pub mod view;' -B 1 src/lib.rs || true)"
if printf '%s' "$VIEW_GATE_LINE" | grep -q 'declarative_view'; then
  echo "  ✅ src/lib.rs gates \`pub mod view\` on the \`declarative_view\` alias"
else
  echo "  ❌ src/lib.rs's \`pub mod view\` does not use the \`declarative_view\` alias:"
  printf '%s\n' "$VIEW_GATE_LINE" | sed 's/^/       /'
  echo "       A hand-written conjunction here can drift from build.rs, so the"
  echo "       opt-out or the stripped-profile rule would stop applying to it."
  ERRORS=$((ERRORS + 1))
fi

BUILD_ALIAS="$(grep -n 'rustc-cfg=declarative_view' build.rs || true)"
if [[ -n "$BUILD_ALIAS" ]]; then
  echo "  ✅ build.rs defines \`declarative_view\`"
else
  echo "  ❌ build.rs does not define the \`declarative_view\` alias"
  ERRORS=$((ERRORS + 1))
fi

# The alias must include the opt-out, or the feature would exist and do nothing.
if grep -q 'view_opted_out' build.rs && grep -q 'no-declarative-view' Cargo.toml; then
  echo "  ✅ the alias honours the \`no-declarative-view\` feature"
else
  echo "  ❌ the \`no-declarative-view\` opt-out is not wired into the alias:"
  echo "       build.rs must read it and Cargo.toml must declare the feature"
  ERRORS=$((ERRORS + 1))
fi

echo ""
if [[ "$ERRORS" -gt 0 ]]; then
  echo "view platform gate: FAILED ($ERRORS finding(s))" >&2
  echo "" >&2
  echo "To confirm this gate can fail (BLUE18 Phase E'-5): re-spell the \`view\` gate" >&2
  echo "in src/lib.rs as \`all(any(desktop, tablet, mobile), widgets_unstripped)\`" >&2
  echo "(dropping the opt-out) and re-run — step [5] must report ❌." >&2
  exit 1
fi

echo "✅ view platform gate passed: the declarative layer is present by default on"
echo "   desktop/tablet/mobile, removable through \`no-declarative-view\`, and absent"
echo "   on mini/embedded and on a profile-less build."

