#!/usr/bin/env python3
"""Generate C header for rust_widgets error codes.

Parses ErrorId constants from src/error/mod.rs and emits
rw_errors.h with stable numeric error codes.
"""

import re
import sys
from pathlib import Path

HEADER_TEMPLATE = """\
// Auto-generated by tools/generate_error_header.py — DO NOT EDIT
// Source: src/error/mod.rs
#ifndef RW_ERRORS_H
#define RW_ERRORS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

/* ------------------------------------------------------------------ */
/* FFI‑safe error codes — stable, append‑only                         */
/* ------------------------------------------------------------------ */
{defines}

/* ------------------------------------------------------------------ */
/* Helpers                                                             */
/* ------------------------------------------------------------------ */

/// Convert an `RwError` to a human‑readable string.  Returns a pointer
/// that MUST be freed with `rw_free_string()`.
const char* rw_error_message(uint64_t handle);

/// Return the numeric error code from an `RwError` handle.
int32_t rw_error_code(uint64_t handle);

#ifdef __cplusplus
}}
#endif

#endif /* RW_ERRORS_H */
"""


def parse_error_constants(source_path: Path) -> list[tuple[str, str, int]]:
    """Parse ErrorId constants from mod.rs.

    Returns list of (const_name, comment, value) tuples.
    """
    constants: list[tuple[str, str, int]] = []
    const_pattern = re.compile(
        r'pub const (\w+):\s*Self\s*=\s*Self\((\d+)\);\s*(?:///(.*))?'
    )
    brace_depth = 0
    in_impl = False
    found_end_brace = False

    with open(source_path, 'r', encoding='utf-8') as f:
        for line in f:
            stripped = line.strip()

            # Detect impl ErrorId block
            if 'impl ErrorId' in stripped:
                in_impl = True
                brace_depth = stripped.count('{') - stripped.count('}')
                continue

            if not in_impl:
                continue

            # Track brace depth to find closing }
            brace_depth += stripped.count('{') - stripped.count('}')
            if brace_depth <= 0 and in_impl:
                found_end_brace = True
                break

            # Skip comment-only lines
            if stripped.startswith('//') or not stripped:
                continue

            m = const_pattern.match(stripped)
            if m:
                name = m.group(1)
                value = int(m.group(2))
                doc = (m.group(3) or '').strip()
                constants.append((name, doc, value))

    return constants


def generate_header(constants: list[tuple[str, str, int]]) -> str:
    """Generate C header content."""
    # Group by value ranges
    general = []
    widget = []
    platform = []
    render_grp = []
    io = []

    for name, doc, value in constants:
        if 0 <= value <= 99:
            general.append((name, doc, value))
        elif 100 <= value <= 199:
            widget.append((name, doc, value))
        elif 200 <= value <= 299:
            platform.append((name, doc, value))
        elif 300 <= value <= 399:
            render_grp.append((name, doc, value))
        elif 400 <= value <= 499:
            io.append((name, doc, value))
        else:
            general.append((name, doc, value))

    lines = []
    groups = [
        ("General", general),
        ("Widget", widget),
        ("Platform", platform),
        ("Render", render_grp),
        ("I/O", io),
    ]

    for group_name, items in groups:
        if not items:
            continue
        lines.append(f'/* --- {group_name} --- */')
        for name, doc, value in items:
            # Convert Rust SCREAMING_CASE to RW_ prefix
            macro_name = f"RW_ERROR_{name}"
            doc_comment = f" /* {doc} */" if doc else ""
            lines.append(f'#define {macro_name:<45} {value}{doc_comment}')
        lines.append('')

    # Add EW_ERROR alias macros to preserve compatibility with EW-prefixed bindings.
    lines.append('/* --- EW aliases --- */')
    for group_name, items in groups:
        for name, _, _ in items:
            rw_macro = f"RW_ERROR_{name}"
            ew_macro = f"EW_ERROR_{name}"
            lines.append(f'#define {ew_macro:<45} {rw_macro}')
        lines.append('')

    defines = '\n'.join(lines)
    return HEADER_TEMPLATE.format(defines=defines)


def main():
    repo_root = Path(__file__).resolve().parent.parent
    source_path = repo_root / 'src' / 'error' / 'mod.rs'
    output_path = repo_root / 'include' / 'rw_errors.h'

    if not source_path.exists():
        print(f"Error: source not found: {source_path}", file=sys.stderr)
        sys.exit(1)

    constants = parse_error_constants(source_path)
    if not constants:
        print("Error: no ErrorId constants found", file=sys.stderr)
        sys.exit(1)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    header = generate_header(constants)
    output_path.write_text(header, encoding='utf-8')
    print(f"Generated {output_path} ({len(constants)} error codes)")


if __name__ == '__main__':
    main()
