// SPDX-FileCopyrightText: Copyright (c) 2026 Mike Li/Mikewolfli/Wei Li(mikewolfli@163.com)
// SPDX-License-Identifier: MIT

//! Generated by `tools/check_view_platform_gate.sh`; the committed file is restored
//! when the gate exits. The import is forced unconditional on purpose: resolving it
//! is the assertion that `crate::view` is compiled into this profile.

#![allow(unused_imports)]
#![allow(dead_code)]

use rust_widgets::view::VIEW_GATE_PROBE;

#[test]
fn view_gate_probe_resolves() {
    assert!(!VIEW_GATE_PROBE.is_empty());
}
