//! Platform abstraction for desktop/embedded/mobile families.

pub mod harmony;
pub mod linux;
#[cfg(not(all(target_os = "macos", feature = "objc2-macos")))]
pub mod macos;
#[cfg(all(target_os = "macos", feature = "objc2-macos"))]
pub mod macos_objc2;
#[cfg(feature = "mobile-api")]
pub mod mobile;
mod state;
pub mod windows;

use std::collections::{HashMap, VecDeque};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Mutex, OnceLock};

use crate::core::{ObjectId, PlatformFamily, RuntimeProfile};

/// Typed widget trigger kinds surfaced by platform backends.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum WidgetTriggerKind {
    /// No concrete trigger semantic is known.
    Unknown = 0,
    /// Primary activation action (button click, checkbox toggle, etc.).
    Clicked = 1,
    /// Stateful value changed (line edit text, slider value, etc.).
    ValueChanged = 2,
    /// Selection changed (combo/list/tree/table current selection updates).
    SelectionChanged = 3,
    /// Widget/window closed lifecycle trigger.
    Closed = 4,
}

/// Typed widget trigger event with source widget id.
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct WidgetTriggerEvent {
    /// Logical widget id generated by the platform abstraction.
    pub widget_id: ObjectId,
    /// Normalized trigger kind for cross-platform consumption.
    pub kind: WidgetTriggerKind,
}

/// Drag-and-drop payload event.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DropEvent {
    /// Logical id of drag source widget.
    pub source_widget_id: ObjectId,
    /// Logical id of drop target widget.
    pub target_widget_id: ObjectId,
    /// MIME type describing payload bytes.
    pub mime: String,
    /// Opaque drag payload bytes.
    pub payload: Vec<u8>,
}

/// Supported desktop backend families.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DesktopBackend {
    /// Windows Win32 backend.
    Win32,
    /// Apple Cocoa backend.
    Cocoa,
    /// Linux GTK backend.
    Gtk,
    /// Harmony desktop backend.
    HarmonyDesktop,
}

/// Supported mobile backend families.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MobileBackend {
    /// Android mobile backend.
    Android,
    /// iOS mobile backend.
    Ios,
    /// Harmony mobile backend.
    HarmonyMobile,
}

/// Cross-platform runtime capability flags.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PlatformCapabilities {
    /// High-DPI scale-aware geometry and text support.
    pub dpi_scaling: bool,
    /// Input method editor integration capability.
    pub ime: bool,
    /// Native accessibility bridge capability.
    pub accessibility: bool,
    /// Native menu creation and trigger support.
    pub native_menu: bool,
    /// Typed widget trigger event support.
    pub typed_widget_trigger: bool,
}

/// Native-runtime capability contract used by desktop-oriented negotiation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct NativeCapabilityContract {
    /// Whether DPI scaling is supported.
    pub dpi_scaling: bool,
    /// Whether IME integration is supported.
    pub ime: bool,
    /// Whether accessibility bridge is supported.
    pub accessibility: bool,
    /// Whether native menu integration is supported.
    pub native_menu: bool,
    /// Whether typed widget triggers are supported.
    pub typed_widget_trigger: bool,
}

/// Embedded-runtime capability contract used by constrained-profile negotiation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EmbeddedCapabilityContract {
    /// Whether the runtime assumes a fixed DPI scale factor.
    pub fixed_dpi: bool,
    /// Whether low-memory behavior is expected by default.
    pub low_memory_mode: bool,
    /// Whether typed widget triggers are supported.
    pub typed_widget_trigger: bool,
}

/// Runtime capability negotiation result split by profile contract.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CapabilityContract {
    Native(NativeCapabilityContract),
    Embedded(EmbeddedCapabilityContract),
}

impl NativeCapabilityContract {
    fn from_platform_caps(caps: PlatformCapabilities) -> Self {
        Self {
            dpi_scaling: caps.dpi_scaling,
            ime: caps.ime,
            accessibility: caps.accessibility,
            native_menu: caps.native_menu,
            typed_widget_trigger: caps.typed_widget_trigger,
        }
    }
}

/// Platform backend contract used by widget/runtime layers.
pub trait Platform: Send + Sync {
    /// Returns backend identifier string.
    fn backend_name(&self) -> &'static str;
    /// Returns platform family classification.
    fn family(&self) -> PlatformFamily;
    /// Runtime capabilities exposed by the current backend.
    fn capabilities(&self) -> PlatformCapabilities {
        let desktop = matches!(self.family(), PlatformFamily::Desktop);
        PlatformCapabilities {
            dpi_scaling: desktop,
            ime: desktop,
            accessibility: desktop,
            native_menu: desktop,
            typed_widget_trigger: true,
        }
    }
    /// Native capability contract published by desktop-capable runtimes.
    fn native_capability_contract(&self) -> Option<NativeCapabilityContract> {
        if matches!(self.family(), PlatformFamily::Desktop) {
            Some(NativeCapabilityContract::from_platform_caps(
                self.capabilities(),
            ))
        } else {
            None
        }
    }
    /// Embedded capability contract published by constrained runtimes.
    fn embedded_capability_contract(&self) -> Option<EmbeddedCapabilityContract> {
        if matches!(self.family(), PlatformFamily::Embedded) {
            Some(EmbeddedCapabilityContract {
                fixed_dpi: self.dpi_scale_factor() == 1.0,
                low_memory_mode: true,
                typed_widget_trigger: self.capabilities().typed_widget_trigger,
            })
        } else {
            None
        }
    }
    /// Logical DPI scale factor for coordinate transforms.
    fn dpi_scale_factor(&self) -> f32 {
        1.0
    }
    fn init(&self);
    fn run(&self);
    fn quit(&self);
    fn create_window(&self, title: &str, x: i32, y: i32, width: u32, height: u32) -> ObjectId;
    fn create_button(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_checkbox(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId {
        self.create_button(parent, text, x, y, width, height)
    }
    fn create_line_edit(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId {
        self.create_button(parent, text, x, y, width, height)
    }
    fn create_label(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId {
        self.create_button(parent, text, x, y, width, height)
    }
    fn create_radio_button(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId {
        self.create_button(parent, text, x, y, width, height)
    }
    fn create_slider(&self, parent: ObjectId, x: i32, y: i32, width: u32, height: u32) -> ObjectId {
        self.create_button(parent, "Slider", x, y, width, height)
    }
    fn create_progress_bar(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId {
        self.create_button(parent, "ProgressBar", x, y, width, height)
    }
    fn create_combo_box(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId {
        self.create_button(parent, "ComboBox", x, y, width, height)
    }
    fn create_list_box(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId {
        self.create_button(parent, "ListBox", x, y, width, height)
    }
    fn create_panel(&self, parent: ObjectId, x: i32, y: i32, width: u32, height: u32) -> ObjectId {
        self.create_button(parent, "Panel", x, y, width, height)
    }
    fn create_menu_bar(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId {
        self.create_button(parent, "MenuBar", x, y, width, height)
    }
    fn create_menu(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId {
        self.create_button(parent, text, x, y, width, height)
    }
    fn attach_menu_bar_to_window(&self, _window: ObjectId, _menu_bar: ObjectId) -> bool {
        false
    }
    fn menu_add_item(
        &self,
        parent_menu: ObjectId,
        text: &str,
        _shortcut: Option<&str>,
    ) -> ObjectId {
        self.create_menu(parent_menu, text, 0, 0, 0, 0)
    }
    /// Poll next menu item trigger if available.
    fn poll_menu_triggered(&self) -> Option<ObjectId> {
        None
    }
    /// Inject a menu trigger from native/external callback source.
    fn inject_menu_trigger(&self, _menu_item_id: ObjectId) -> bool {
        false
    }
    /// Poll next widget id trigger if available.
    fn poll_widget_triggered(&self) -> Option<ObjectId> {
        None
    }
    /// Poll a typed widget trigger event.
    fn poll_widget_trigger_event(&self) -> Option<WidgetTriggerEvent> {
        self.poll_widget_triggered()
            .map(|widget_id| WidgetTriggerEvent {
                widget_id,
                kind: WidgetTriggerKind::Unknown,
            })
    }
    /// Inject a typed widget trigger from native/external callback source.
    fn inject_widget_trigger_event(&self, _widget_id: ObjectId, _kind: WidgetTriggerKind) -> bool {
        false
    }
    fn create_tool_bar(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId {
        self.create_button(parent, "ToolBar", x, y, width, height)
    }
    fn create_status_bar(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId {
        self.create_button(parent, text, x, y, width, height)
    }
    fn show_widget(&self, widget_id: ObjectId);
    fn hide_widget(&self, widget_id: ObjectId);
    fn set_widget_geometry(&self, widget_id: ObjectId, x: i32, y: i32, width: u32, height: u32);
    fn set_widget_text(&self, widget_id: ObjectId, text: &str);
    fn get_widget_text(&self, widget_id: ObjectId) -> String;
    fn set_widget_enabled(&self, widget_id: ObjectId, enabled: bool);
    fn is_widget_enabled(&self, widget_id: ObjectId) -> bool;
    fn set_widget_visible(&self, widget_id: ObjectId, visible: bool);
    fn is_widget_visible(&self, widget_id: ObjectId) -> bool;

    /// Enable or disable IME input handling for a widget.
    fn set_widget_ime_enabled(&self, _widget_id: ObjectId, _enabled: bool) -> bool {
        false
    }

    /// Query IME enabled state for a widget.
    fn is_widget_ime_enabled(&self, _widget_id: ObjectId) -> bool {
        false
    }

    /// Set accessibility name/label for a widget.
    fn set_widget_accessibility_name(&self, _widget_id: ObjectId, _name: &str) -> bool {
        false
    }

    /// Read accessibility name/label for a widget.
    fn get_widget_accessibility_name(&self, _widget_id: ObjectId) -> String {
        String::new()
    }

    /// Set plain text clipboard content.
    fn set_clipboard_text(&self, _text: &str) -> bool {
        false
    }

    /// Read plain text clipboard content.
    fn get_clipboard_text(&self) -> String {
        String::new()
    }

    /// Start a drag operation from source widget.
    fn begin_drag(&self, _source_widget_id: ObjectId, _mime: &str, _payload: &[u8]) -> bool {
        false
    }

    /// Poll next drop event if available.
    fn poll_drop_event(&self) -> Option<DropEvent> {
        None
    }

    /// Inject drop event into backend queue.
    fn inject_drop_event(&self, _event: DropEvent) -> bool {
        false
    }
}

/// Optional mobile-specific extension contract.
pub trait MobilePlatformExtension: Send + Sync {
    /// Returns the active mobile backend family.
    fn mobile_backend(&self) -> MobileBackend;
    /// Attaches runtime to an externally provided native view handle.
    fn attach_to_native_view(&self, _native_handle: usize) -> bool;
}

#[derive(Default)]
struct WidgetState {
    text: String,
    visible: bool,
    enabled: bool,
    ime_enabled: bool,
    accessibility_name: String,
    x: i32,
    y: i32,
    width: u32,
    height: u32,
}

struct MenuNodeState {
    text: String,
}

/// In-memory test/dummy backend implementing the `Platform` contract.
pub struct StubPlatform {
    backend: &'static str,
    family: PlatformFamily,
    next_id: AtomicU64,
    widgets: Mutex<HashMap<ObjectId, WidgetState>>,
    menu_nodes: Mutex<HashMap<ObjectId, MenuNodeState>>,
    menu_events: Mutex<VecDeque<ObjectId>>,
    /// Queue used by injection APIs and test/demo bridge paths.
    widget_events: Mutex<VecDeque<WidgetTriggerEvent>>,
    /// Process-local clipboard text fallback.
    clipboard_text: Mutex<String>,
    /// Drag-drop event queue for backend adapters/tests.
    drop_events: Mutex<VecDeque<DropEvent>>,
}

impl StubPlatform {
    /// Creates a new in-memory stub backend for tests and demos.
    pub fn new(backend: &'static str, family: PlatformFamily) -> Self {
        Self {
            backend,
            family,
            next_id: AtomicU64::new(1),
            widgets: Mutex::new(HashMap::new()),
            menu_nodes: Mutex::new(HashMap::new()),
            menu_events: Mutex::new(VecDeque::new()),
            widget_events: Mutex::new(VecDeque::new()),
            clipboard_text: Mutex::new(String::new()),
            drop_events: Mutex::new(VecDeque::new()),
        }
    }

    fn new_id(&self) -> ObjectId {
        self.next_id.fetch_add(1, Ordering::Relaxed)
    }
}

impl Platform for StubPlatform {
    fn backend_name(&self) -> &'static str {
        self.backend
    }
    fn family(&self) -> PlatformFamily {
        self.family
    }
    fn init(&self) {}
    fn run(&self) {}
    fn quit(&self) {}

    fn create_window(&self, title: &str, x: i32, y: i32, width: u32, height: u32) -> ObjectId {
        let id = self.new_id();
        self.widgets.lock().expect("platform lock poisoned").insert(
            id,
            WidgetState {
                text: title.to_string(),
                visible: true,
                enabled: true,
                ime_enabled: true,
                accessibility_name: title.to_string(),
                x,
                y,
                width,
                height,
            },
        );
        id
    }

    fn create_button(
        &self,
        _parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId {
        let id = self.new_id();
        self.widgets.lock().expect("platform lock poisoned").insert(
            id,
            WidgetState {
                text: text.to_string(),
                visible: true,
                enabled: true,
                ime_enabled: true,
                accessibility_name: text.to_string(),
                x,
                y,
                width,
                height,
            },
        );
        id
    }

    fn create_menu_bar(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId {
        let id = self.create_button(parent, "MenuBar", x, y, width, height);
        self.menu_nodes
            .lock()
            .expect("platform lock poisoned")
            .insert(
                id,
                MenuNodeState {
                    text: "MenuBar".to_string(),
                },
            );
        id
    }

    fn create_menu(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId {
        let id = self.create_button(parent, text, x, y, width, height);
        self.menu_nodes
            .lock()
            .expect("platform lock poisoned")
            .insert(
                id,
                MenuNodeState {
                    text: text.to_string(),
                },
            );
        id
    }

    fn attach_menu_bar_to_window(&self, window: ObjectId, menu_bar: ObjectId) -> bool {
        let widgets = self.widgets.lock().expect("platform lock poisoned");
        widgets.contains_key(&window) && widgets.contains_key(&menu_bar)
    }

    fn menu_add_item(&self, parent_menu: ObjectId, text: &str, shortcut: Option<&str>) -> ObjectId {
        let id = self.create_menu(parent_menu, text, 0, 0, 0, 0);
        self.menu_nodes
            .lock()
            .expect("platform lock poisoned")
            .insert(
                id,
                MenuNodeState {
                    text: text.to_string(),
                },
            );
        let _ = shortcut;
        id
    }

    fn poll_menu_triggered(&self) -> Option<ObjectId> {
        let mut events = self.menu_events.lock().expect("platform lock poisoned");
        events.pop_front()
    }

    fn inject_menu_trigger(&self, menu_item_id: ObjectId) -> bool {
        // Accept only known menu ids to avoid emitting orphan events.
        if !self
            .menu_nodes
            .lock()
            .expect("platform lock poisoned")
            .contains_key(&menu_item_id)
        {
            return false;
        }
        self.menu_events
            .lock()
            .expect("platform lock poisoned")
            .push_back(menu_item_id);
        true
    }

    fn poll_widget_triggered(&self) -> Option<ObjectId> {
        self.poll_widget_trigger_event()
            .map(|event| event.widget_id)
    }

    fn poll_widget_trigger_event(&self) -> Option<WidgetTriggerEvent> {
        self.widget_events
            .lock()
            .expect("platform lock poisoned")
            .pop_front()
    }

    fn inject_widget_trigger_event(&self, widget_id: ObjectId, kind: WidgetTriggerKind) -> bool {
        // Accept only known widget ids to keep queue semantics deterministic.
        if !self
            .widgets
            .lock()
            .expect("platform lock poisoned")
            .contains_key(&widget_id)
        {
            return false;
        }
        self.widget_events
            .lock()
            .expect("platform lock poisoned")
            .push_back(WidgetTriggerEvent { widget_id, kind });
        true
    }

    fn show_widget(&self, widget_id: ObjectId) {
        if let Some(widget) = self
            .widgets
            .lock()
            .expect("platform lock poisoned")
            .get_mut(&widget_id)
        {
            widget.visible = true;
        }
    }

    fn hide_widget(&self, widget_id: ObjectId) {
        if let Some(widget) = self
            .widgets
            .lock()
            .expect("platform lock poisoned")
            .get_mut(&widget_id)
        {
            widget.visible = false;
        }
    }

    fn set_widget_geometry(&self, widget_id: ObjectId, x: i32, y: i32, width: u32, height: u32) {
        if let Some(widget) = self
            .widgets
            .lock()
            .expect("platform lock poisoned")
            .get_mut(&widget_id)
        {
            widget.x = x;
            widget.y = y;
            widget.width = width;
            widget.height = height;
        }
    }

    fn set_widget_text(&self, widget_id: ObjectId, text: &str) {
        if let Some(widget) = self
            .widgets
            .lock()
            .expect("platform lock poisoned")
            .get_mut(&widget_id)
        {
            widget.text = text.to_string();
        }
        if let Some(node) = self
            .menu_nodes
            .lock()
            .expect("platform lock poisoned")
            .get_mut(&widget_id)
        {
            node.text = text.to_string();
        }
    }

    fn get_widget_text(&self, widget_id: ObjectId) -> String {
        self.widgets
            .lock()
            .expect("platform lock poisoned")
            .get(&widget_id)
            .map(|widget| widget.text.clone())
            .unwrap_or_default()
    }

    fn set_widget_enabled(&self, widget_id: ObjectId, enabled: bool) {
        if let Some(widget) = self
            .widgets
            .lock()
            .expect("platform lock poisoned")
            .get_mut(&widget_id)
        {
            widget.enabled = enabled;
        }
    }

    fn is_widget_enabled(&self, widget_id: ObjectId) -> bool {
        self.widgets
            .lock()
            .expect("platform lock poisoned")
            .get(&widget_id)
            .map(|widget| widget.enabled)
            .unwrap_or(false)
    }

    fn set_widget_visible(&self, widget_id: ObjectId, visible: bool) {
        if let Some(widget) = self
            .widgets
            .lock()
            .expect("platform lock poisoned")
            .get_mut(&widget_id)
        {
            widget.visible = visible;
        }
    }

    fn is_widget_visible(&self, widget_id: ObjectId) -> bool {
        self.widgets
            .lock()
            .expect("platform lock poisoned")
            .get(&widget_id)
            .map(|widget| widget.visible)
            .unwrap_or(false)
    }

    fn set_widget_ime_enabled(&self, widget_id: ObjectId, enabled: bool) -> bool {
        if let Some(widget) = self
            .widgets
            .lock()
            .expect("platform lock poisoned")
            .get_mut(&widget_id)
        {
            widget.ime_enabled = enabled;
            return true;
        }
        false
    }

    fn is_widget_ime_enabled(&self, widget_id: ObjectId) -> bool {
        self.widgets
            .lock()
            .expect("platform lock poisoned")
            .get(&widget_id)
            .map(|widget| widget.ime_enabled)
            .unwrap_or(false)
    }

    fn set_widget_accessibility_name(&self, widget_id: ObjectId, name: &str) -> bool {
        if let Some(widget) = self
            .widgets
            .lock()
            .expect("platform lock poisoned")
            .get_mut(&widget_id)
        {
            widget.accessibility_name = name.to_string();
            return true;
        }
        false
    }

    fn get_widget_accessibility_name(&self, widget_id: ObjectId) -> String {
        self.widgets
            .lock()
            .expect("platform lock poisoned")
            .get(&widget_id)
            .map(|widget| widget.accessibility_name.clone())
            .unwrap_or_default()
    }

    fn set_clipboard_text(&self, text: &str) -> bool {
        *self
            .clipboard_text
            .lock()
            .expect("platform clipboard lock poisoned") = text.to_string();
        true
    }

    fn get_clipboard_text(&self) -> String {
        self.clipboard_text
            .lock()
            .expect("platform clipboard lock poisoned")
            .clone()
    }

    fn begin_drag(&self, source_widget_id: ObjectId, mime: &str, payload: &[u8]) -> bool {
        if !self
            .widgets
            .lock()
            .expect("platform lock poisoned")
            .contains_key(&source_widget_id)
        {
            return false;
        }

        self.drop_events
            .lock()
            .expect("platform drop lock poisoned")
            .push_back(DropEvent {
                source_widget_id,
                target_widget_id: source_widget_id,
                mime: mime.to_string(),
                payload: payload.to_vec(),
            });
        true
    }

    fn poll_drop_event(&self) -> Option<DropEvent> {
        self.drop_events
            .lock()
            .expect("platform drop lock poisoned")
            .pop_front()
    }

    fn inject_drop_event(&self, event: DropEvent) -> bool {
        if !self
            .widgets
            .lock()
            .expect("platform lock poisoned")
            .contains_key(&event.target_widget_id)
        {
            return false;
        }

        self.drop_events
            .lock()
            .expect("platform drop lock poisoned")
            .push_back(event);
        true
    }
}

#[cfg(target_os = "windows")]
fn create_native_platform() -> Box<dyn Platform> {
    Box::new(windows::WindowsPlatform::new())
}

/// Select objc2 preview backend when migration feature is enabled on macOS.
#[cfg(all(target_os = "macos", feature = "objc2-macos"))]
fn create_native_platform() -> Box<dyn Platform> {
    Box::new(macos_objc2::MacOSObjc2Platform::new())
}

/// Select legacy Cocoa backend when objc2 migration feature is disabled.
#[cfg(all(target_os = "macos", not(feature = "objc2-macos")))]
fn create_native_platform() -> Box<dyn Platform> {
    Box::new(macos::MacOSPlatform::new())
}

#[cfg(target_os = "linux")]
fn create_native_platform() -> Box<dyn Platform> {
    Box::new(linux::LinuxPlatform::new())
}

#[cfg(not(any(target_os = "windows", target_os = "macos", target_os = "linux")))]
fn create_native_platform() -> Box<dyn Platform> {
    Box::new(harmony::HarmonyPlatform::new())
}

static PLATFORM: OnceLock<Box<dyn Platform>> = OnceLock::new();

/// Returns the process-global platform backend instance.
pub fn get_platform() -> &'static dyn Platform {
    PLATFORM.get_or_init(create_native_platform).as_ref()
}

/// Initializes the platform backend.
pub fn init() {
    get_platform().init();
}
/// Runs the platform main loop.
pub fn run() {
    get_platform().run();
}
/// Requests platform main loop shutdown.
pub fn quit() {
    get_platform().quit();
}
/// Returns runtime capabilities for the active backend.
pub fn capabilities() -> PlatformCapabilities {
    get_platform().capabilities()
}
/// Returns logical DPI scale factor for the active backend.
pub fn dpi_scale_factor() -> f32 {
    get_platform().dpi_scale_factor()
}

#[cfg(feature = "mobile-api")]
/// Returns the mobile backend name.
pub fn mobile_backend_name() -> &'static str {
    mobile::get_mobile_platform().backend_name()
}

#[cfg(feature = "mobile-api")]
/// Attaches the mobile backend to a native view handle.
pub fn mobile_attach_to_native_view(native_handle: usize) -> bool {
    mobile::get_mobile_platform().attach_to_native_view(native_handle)
}

fn fallback_native_capability_contract() -> NativeCapabilityContract {
    NativeCapabilityContract {
        dpi_scaling: true,
        ime: true,
        accessibility: true,
        native_menu: true,
        typed_widget_trigger: true,
    }
}

fn fallback_embedded_capability_contract() -> EmbeddedCapabilityContract {
    EmbeddedCapabilityContract {
        fixed_dpi: true,
        low_memory_mode: true,
        typed_widget_trigger: true,
    }
}

/// Negotiate capabilities using profile-specific contracts with deterministic fallbacks.
pub fn negotiate_capability_contract(profile: RuntimeProfile) -> CapabilityContract {
    match profile {
        RuntimeProfile::Full => get_platform()
            .native_capability_contract()
            .map(CapabilityContract::Native)
            .unwrap_or(CapabilityContract::Native(
                fallback_native_capability_contract(),
            )),
        RuntimeProfile::Embedded => get_platform()
            .embedded_capability_contract()
            .map(CapabilityContract::Embedded)
            .unwrap_or(CapabilityContract::Embedded(
                fallback_embedded_capability_contract(),
            )),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn consistency_menu_trigger_roundtrip() {
        let platform = StubPlatform::new("test-desktop", PlatformFamily::Desktop);
        let window = platform.create_window("w", 0, 0, 100, 100);
        let menu_bar = platform.create_menu_bar(window, 0, 0, 100, 20);
        let menu = platform.create_menu(menu_bar, "File", 0, 0, 50, 20);
        let item = platform.menu_add_item(menu, "Open", None);

        assert!(platform.inject_menu_trigger(item));
        assert_eq!(platform.poll_menu_triggered(), Some(item));
    }

    #[test]
    fn consistency_typed_widget_trigger_roundtrip() {
        let platform = StubPlatform::new("test-desktop", PlatformFamily::Desktop);
        let window = platform.create_window("w", 0, 0, 100, 100);
        let button = platform.create_button(window, "btn", 0, 0, 80, 30);

        assert!(platform.inject_widget_trigger_event(button, WidgetTriggerKind::Clicked));
        assert_eq!(
            platform.poll_widget_trigger_event(),
            Some(WidgetTriggerEvent {
                widget_id: button,
                kind: WidgetTriggerKind::Clicked,
            })
        );
    }

    #[test]
    fn consistency_compat_poll_widget_triggered_is_single_delivery_shim() {
        let platform = StubPlatform::new("test-desktop", PlatformFamily::Desktop);
        let window = platform.create_window("w", 0, 0, 100, 100);
        let button = platform.create_button(window, "btn", 0, 0, 80, 30);

        assert!(platform.inject_widget_trigger_event(button, WidgetTriggerKind::Clicked));
        assert_eq!(platform.poll_widget_triggered(), Some(button));
        assert_eq!(platform.poll_widget_triggered(), None);
        assert_eq!(platform.poll_widget_trigger_event(), None);
    }

    #[test]
    fn consistency_capability_contract_by_profile() {
        let desktop = StubPlatform::new("test-desktop", PlatformFamily::Desktop);
        let embedded = StubPlatform::new("test-embedded", PlatformFamily::Embedded);

        assert!(desktop.native_capability_contract().is_some());
        assert!(desktop.embedded_capability_contract().is_none());

        assert!(embedded.native_capability_contract().is_none());
        assert!(embedded.embedded_capability_contract().is_some());
    }
}
