//! Platform abstraction types and capability contracts.

use crate::core::{ObjectId, PlatformFamily};
#[cfg(all(feature = "serde", not(any(feature = "mini", feature = "embedded"))))]
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(
    all(feature = "serde", not(any(feature = "mini", feature = "embedded"))),
    derive(Serialize, Deserialize)
)]
pub enum WidgetTriggerKind {
    /// No concrete trigger semantic is known.
    Unknown = 0,
    /// Primary activation action (button click, checkbox toggle, etc.).
    Clicked = 1,
    /// Stateful value changed (line edit text, slider value, etc.).
    ValueChanged = 2,
    /// Selection changed (combo/list/tree/table current selection updates).
    SelectionChanged = 3,
    /// Widget/window closed lifecycle trigger.
    Closed = 4,
}
/// Typed widget trigger event with source widget id.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(
    all(feature = "serde", not(any(feature = "mini", feature = "embedded"))),
    derive(Serialize, Deserialize)
)]
pub struct WidgetTriggerEvent {
    /// Logical widget id generated by the platform abstraction.
    pub widget_id: ObjectId,
    /// Normalized trigger kind for cross-platform consumption.
    pub kind: WidgetTriggerKind,
}
/// Drag-and-drop payload event.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(
    all(feature = "serde", not(any(feature = "mini", feature = "embedded"))),
    derive(Serialize, Deserialize)
)]
pub struct DropEvent {
    /// Logical id of drag source widget.
    pub source_widget_id: ObjectId,
    /// Logical id of drop target widget.
    pub target_widget_id: ObjectId,
    /// MIME type describing payload bytes.
    pub mime: String,
    /// Opaque drag payload bytes.
    pub payload: Vec<u8>,
}
/// Supported desktop backend families.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DesktopBackend {
    /// Windows Win32 backend.
    Win32,
    /// Apple Cocoa backend.
    Cocoa,
    /// Linux GTK backend.
    Gtk,
    /// Harmony desktop backend.
    HarmonyDesktop,
}
/// Supported mobile backend families.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MobileBackend {
    /// Android mobile backend.
    Android,
    /// iOS mobile backend.
    Ios,
    /// Harmony mobile backend.
    HarmonyMobile,
}
/// Cross-platform runtime capability flags.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PlatformCapabilities {
    /// High-DPI scale-aware geometry and text support.
    pub dpi_scaling: bool,
    /// Input method editor integration capability.
    pub ime: bool,
    /// Native accessibility bridge capability.
    pub accessibility: bool,
    /// Native menu creation and trigger support.
    pub native_menu: bool,
    /// Typed widget trigger event support.
    pub typed_widget_trigger: bool,
}
/// Native-runtime capability contract used by desktop-oriented negotiation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct NativeCapabilityContract {
    /// Whether DPI scaling is supported.
    pub dpi_scaling: bool,
    /// Whether IME integration is supported.
    pub ime: bool,
    /// Whether accessibility bridge is supported.
    pub accessibility: bool,
    /// Whether native menu integration is supported.
    pub native_menu: bool,
    /// Whether typed widget triggers are supported.
    pub typed_widget_trigger: bool,
}
/// Embedded-runtime capability contract used by constrained-profile negotiation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EmbeddedCapabilityContract {
    /// Whether the runtime assumes a fixed DPI scale factor.
    pub fixed_dpi: bool,
    /// Whether low-memory behavior is expected by default.
    pub low_memory_mode: bool,
    /// Whether typed widget triggers are supported.
    pub typed_widget_trigger: bool,
}
/// Runtime capability negotiation result split by profile contract.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CapabilityContract {
    Native(NativeCapabilityContract),
    Embedded(EmbeddedCapabilityContract),
}
impl NativeCapabilityContract {
    pub(crate) fn from_platform_caps(caps: PlatformCapabilities) -> Self {
        Self {
            dpi_scaling: caps.dpi_scaling,
            ime: caps.ime,
            accessibility: caps.accessibility,
            native_menu: caps.native_menu,
            typed_widget_trigger: caps.typed_widget_trigger,
        }
    }
}
/// Platform backend contract used by widget/runtime layers.
///
/// Core lifecycle methods are required. Optional capabilities (IME,
/// accessibility, drag-and-drop) have default no-op implementations
/// on the Platform trait itself — backends override them when supported.
pub trait Platform: Send + Sync {
    /// Returns self as a `&dyn Any` for downcasting.
    fn as_any(&self) -> &dyn core::any::Any {
        // Safe fallback — unsized coercion on a unit type avoids panicking.
        // Concrete backends should override with a self-referencing impl.
        static UNIT: () = ();
        &UNIT as &dyn core::any::Any
    }
    /// Returns backend identifier string.
    fn backend_name(&self) -> &'static str;
    /// Returns platform family classification.
    fn family(&self) -> PlatformFamily;
    /// Runtime capabilities exposed by the current backend.
    fn capabilities(&self) -> PlatformCapabilities {
        let desktop = matches!(self.family(), PlatformFamily::Desktop);
        PlatformCapabilities {
            dpi_scaling: desktop,
            ime: desktop,
            accessibility: desktop,
            native_menu: desktop,
            typed_widget_trigger: true,
        }
    }
    /// Native capability contract published by desktop-capable runtimes.
    fn native_capability_contract(&self) -> Option<NativeCapabilityContract> {
        if matches!(self.family(), PlatformFamily::Desktop) {
            Some(NativeCapabilityContract::from_platform_caps(self.capabilities()))
        } else {
            None
        }
    }
    /// Embedded capability contract published by constrained runtimes.
    fn embedded_capability_contract(&self) -> Option<EmbeddedCapabilityContract> {
        if matches!(self.family(), PlatformFamily::Embedded) {
            Some(EmbeddedCapabilityContract {
                fixed_dpi: self.dpi_scale_factor() == 1.0,
                low_memory_mode: true,
                typed_widget_trigger: self.capabilities().typed_widget_trigger,
            })
        } else {
            None
        }
    }
    /// Logical DPI scale factor for coordinate transforms.
    fn dpi_scale_factor(&self) -> f32 {
        1.0
    }
    fn init(&self);
    fn run(&self);
    fn quit(&self);
    fn create_window(&self, title: &str, x: i32, y: i32, width: u32, height: u32) -> ObjectId;
    fn create_button(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_checkbox(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_line_edit(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_label(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_radio_button(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_slider(&self, parent: ObjectId, x: i32, y: i32, width: u32, height: u32) -> ObjectId;
    fn create_progress_bar(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_combo_box(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn combo_box_add_item(&self, combo_box: ObjectId, _text: &str) -> bool;
    fn combo_box_clear_items(&self, combo_box: ObjectId) -> bool;
    fn combo_box_set_current_index(&self, combo_box: ObjectId, index: usize) -> bool;
    fn combo_box_current_index(&self, combo_box: ObjectId) -> Option<usize>;
    fn combo_box_item_count(&self, combo_box: ObjectId) -> usize;
    fn combo_box_item_text(&self, combo_box: ObjectId, index: usize) -> Option<String>;
    fn create_list_box(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn list_box_add_item(&self, list_box: ObjectId, text: &str) -> bool;
    fn list_box_remove_item(&self, list_box: ObjectId, index: usize) -> bool;
    fn list_box_clear_items(&self, list_box: ObjectId) -> bool;
    fn list_box_set_current_index(&self, list_box: ObjectId, index: usize) -> bool;
    fn list_box_current_index(&self, list_box: ObjectId) -> Option<usize>;
    fn list_box_item_count(&self, list_box: ObjectId) -> usize;
    fn list_box_item_text(&self, list_box: ObjectId, index: usize) -> Option<String>;
    fn create_panel(&self, parent: ObjectId, x: i32, y: i32, width: u32, height: u32) -> ObjectId;
    fn create_menu_bar(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_menu(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn attach_menu_bar_to_window(&self, window: ObjectId, menu_bar: ObjectId) -> bool;
    fn menu_add_item(&self, parent_menu: ObjectId, text: &str, shortcut: Option<&str>) -> ObjectId;
    fn poll_menu_triggered(&self) -> Option<ObjectId>;
    fn inject_menu_trigger(&self, menu_item_id: ObjectId) -> bool;
    fn poll_widget_triggered(&self) -> Option<ObjectId>;
    fn poll_widget_trigger_event(&self) -> Option<WidgetTriggerEvent>;
    fn inject_widget_trigger_event(&self, widget_id: ObjectId, kind: WidgetTriggerKind) -> bool;
    fn create_tool_bar(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_status_bar(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    #[allow(clippy::too_many_arguments)]
    fn create_message_box(
        &self,
        parent: ObjectId,
        title: &str,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_file_dialog(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_color_dialog(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_font_dialog(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_spin_box(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_list_view(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_scroll_area(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn show_widget(&self, widget_id: ObjectId);
    fn hide_widget(&self, widget_id: ObjectId);
    fn set_widget_geometry(&self, widget_id: ObjectId, x: i32, y: i32, width: u32, height: u32);
    fn set_widget_text(&self, widget_id: ObjectId, text: &str);
    fn get_widget_text(&self, widget_id: ObjectId) -> String;
    fn set_widget_enabled(&self, widget_id: ObjectId, enabled: bool);
    fn is_widget_enabled(&self, widget_id: ObjectId) -> bool;
    fn set_widget_visible(&self, widget_id: ObjectId, visible: bool);
    fn is_widget_visible(&self, widget_id: ObjectId) -> bool;
    /// Enable or disable IME input handling for a widget.
    fn set_widget_ime_enabled(&self, _widget_id: ObjectId, _enabled: bool) -> bool {
        false
    }
    /// Query IME enabled state for a widget.
    fn is_widget_ime_enabled(&self, _widget_id: ObjectId) -> bool {
        false
    }
    /// Returns a reference to the platform's IME bridge, if available.
    fn ime_bridge(&self) -> Option<&dyn crate::platform::ime::ImeBridge> {
        None
    }
    /// Set accessibility name/label for a widget.
    fn set_widget_accessibility_name(&self, _widget_id: ObjectId, _name: &str) -> bool {
        false
    }
    /// Read accessibility name/label for a widget.
    fn get_widget_accessibility_name(&self, _widget_id: ObjectId) -> String {
        String::new()
    }
    /// Returns a reference to the platform's accessibility bridge, if available.
    fn accessibility_bridge(
        &self,
    ) -> Option<&dyn crate::platform::accessibility::AccessibilityBridge> {
        None
    }

    /// Returns a reference to the platform's rich clipboard backend, if available.
    fn clipboard_backend(&self) -> Option<&dyn crate::platform::clipboard::RichClipboardBackend> {
        None
    }
    /// Set plain text clipboard content.
    fn set_clipboard_text(&self, _text: &str) -> bool {
        false
    }
    /// Read plain text clipboard content.
    fn get_clipboard_text(&self) -> String {
        String::new()
    }
    /// Start a drag operation from source widget.
    fn begin_drag(&self, _source_widget_id: ObjectId, _mime: &str, _payload: &[u8]) -> bool {
        false
    }
    /// Poll next drop event if available.
    fn poll_drop_event(&self) -> Option<DropEvent> {
        None
    }
    /// Inject drop event into backend queue.
    fn inject_drop_event(&self, _event: DropEvent) -> bool {
        false
    }
}
/// Optional mobile-specific extension contract.
pub trait MobilePlatformExtension: Send + Sync {
    /// Returns the active mobile backend family.
    fn mobile_backend(&self) -> MobileBackend;
    /// Attaches runtime to an externally provided native view handle.
    fn attach_to_native_view(&self, _native_handle: usize) -> bool;
}

#[derive(Debug)]
pub(crate) struct MenuNodeState {
    pub(crate) text: String,
}
