// SPDX-FileCopyrightText: Copyright (c) 2026 Mike Li/Mikewolfli/Wei Li(mikewolfli@163.com)
// SPDX-License-Identifier: MIT

//! Platform abstraction types and capability contracts.

use crate::core::{ObjectId, PlatformFamily};
#[cfg(all(feature = "serde", not(any(feature = "mini", feature = "embedded"))))]
use serde::{Deserialize, Serialize};

/// Whether the CUPS print clients (`lp` or `lpr`) are installed.
///
/// Shared by the Unix-oriented backends (macOS, Linux, Wayland) so the detection
/// rule lives in exactly one place. iOS/Android/Harmony do not use it — they print
/// through platform frameworks rather than a spooler command — and the WASM
/// backend has no process to spawn at all.
///
/// The test is whether the binary can be **spawned**, not whether it exits zero:
/// CUPS `lp` rejects `--version` with exit status 1 while still printing its
/// usage text, so an exit-code check would wrongly report "no spooler" on a
/// machine that has one. Only a spawn failure (`ErrorKind::NotFound`) means the
/// binary is absent.
///
/// `allow(dead_code)` rather than a `cfg` gate: the callers live in
/// `platform/{macos,macos_objc2,linux,wayland}`, which are individually
/// `cfg`-gated. Enumerating those same conditions here would duplicate four
/// separate gate expressions — exactly the drift that caused the `full_widgets`
/// bug — so the helper stays available to all targets and simply goes unused on
/// the rest.
#[allow(dead_code)]
pub(crate) fn unix_print_clients_available() -> bool {
    ["lp", "lpr"].iter().any(|cmd| {
        // Any `ExitStatus` at all proves the executable exists and ran.
        std::process::Command::new(cmd).arg("--help").output().is_ok()
    })
}

/// The shortcut notation matching the OS this crate is compiled for.
///
/// Apple platforms use AppKit glyphs (`⌘⇧Z`); everything else uses the spelled-out
/// `Ctrl+Shift+Z` convention. This is the one place the compile target decides the
/// notation, keeping the `cfg!` out of `src/shortcut/` (principle #36). Backends
/// may override it through `Platform::shortcut_style`.
pub const fn compile_target_shortcut_style() -> crate::shortcut::PlatformShortcutStyle {
    if cfg!(any(target_os = "macos", target_os = "ios")) {
        crate::shortcut::PlatformShortcutStyle::Mac
    } else {
        crate::shortcut::PlatformShortcutStyle::Desktop
    }
}

/// A backend-owned native web engine view.
///
/// Widgets in `src/web/` drive a real browser engine through this trait without
/// naming any platform library. The concrete type (a `webkit2gtk::WebView` on the
/// Linux GTK backend) is constructed by the backend and never appears in the
/// widget layer — see principle #36.
///
/// All methods report failure through enums or `Result` rather than panicking:
/// a headless CI host has no display, and that must surface as "no engine" so the
/// caller can fall back to the simulated path.
pub trait NativeWebEngine: Send {
    /// Begins loading `url`.
    fn load_url(&mut self, url: &str) -> Result<(), String>;
    /// Begins loading `html`, optionally resolving relative references against
    /// `base_url`.
    fn load_html(&mut self, html: &str, base_url: Option<&str>) -> Result<(), String>;
    /// Navigates back in the session history.
    fn go_back(&mut self);
    /// Navigates forward in the session history.
    fn go_forward(&mut self);
    /// Reloads the current document.
    fn reload(&mut self);
    /// Cancels an in-flight page load.
    fn stop_loading(&mut self);
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(
    all(feature = "serde", not(any(feature = "mini", feature = "embedded"))),
    derive(Serialize, Deserialize)
)]
pub enum WidgetTriggerKind {
    /// No concrete trigger semantic is known.
    Unknown = 0,
    /// Primary activation action (button click, checkbox toggle, etc.).
    Clicked = 1,
    /// Stateful value changed (line edit text, slider value, etc.).
    ValueChanged = 2,
    /// Selection changed (combo/list/tree/table current selection updates).
    SelectionChanged = 3,
    /// Widget/window closed lifecycle trigger.
    Closed = 4,
}
/// Typed widget trigger event with source widget id.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(
    all(feature = "serde", not(any(feature = "mini", feature = "embedded"))),
    derive(Serialize, Deserialize)
)]
pub struct WidgetTriggerEvent {
    /// Logical widget id generated by the platform abstraction.
    pub widget_id: ObjectId,
    /// Normalized trigger kind for cross-platform consumption.
    pub kind: WidgetTriggerKind,
}
/// Drag-and-drop payload event.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(
    all(feature = "serde", not(any(feature = "mini", feature = "embedded"))),
    derive(Serialize, Deserialize)
)]
pub struct DropEvent {
    /// Logical id of drag source widget.
    pub source_widget_id: ObjectId,
    /// Logical id of drop target widget.
    pub target_widget_id: ObjectId,
    /// MIME type describing payload bytes.
    pub mime: String,
    /// Opaque drag payload bytes.
    pub payload: Vec<u8>,
}
/// Supported desktop backend families.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DesktopBackend {
    /// Windows Win32 backend.
    Win32,
    /// Apple Cocoa backend.
    Cocoa,
    /// Linux GTK backend.
    Gtk,
    /// Harmony desktop backend.
    HarmonyDesktop,
}
/// Supported mobile backend families.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MobileBackend {
    /// Android mobile backend.
    Android,
    /// iOS mobile backend.
    Ios,
    /// Harmony mobile backend.
    HarmonyMobile,
}
/// Cross-platform runtime capability flags.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PlatformCapabilities {
    /// High-DPI scale-aware geometry and text support.
    pub dpi_scaling: bool,
    /// Input method editor integration capability.
    pub ime: bool,
    /// Native accessibility bridge capability.
    pub accessibility: bool,
    /// Native menu creation and trigger support.
    pub native_menu: bool,
    /// Typed widget trigger event support.
    pub typed_widget_trigger: bool,
}
/// Native-runtime capability contract used by desktop-oriented negotiation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct NativeCapabilityContract {
    /// Whether DPI scaling is supported.
    pub dpi_scaling: bool,
    /// Whether IME integration is supported.
    pub ime: bool,
    /// Whether accessibility bridge is supported.
    pub accessibility: bool,
    /// Whether native menu integration is supported.
    pub native_menu: bool,
    /// Whether typed widget triggers are supported.
    pub typed_widget_trigger: bool,
}
/// Embedded-runtime capability contract used by constrained-profile negotiation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EmbeddedCapabilityContract {
    /// Whether the runtime assumes a fixed DPI scale factor.
    pub fixed_dpi: bool,
    /// Whether low-memory behavior is expected by default.
    pub low_memory_mode: bool,
    /// Whether typed widget triggers are supported.
    pub typed_widget_trigger: bool,
}
/// Runtime capability negotiation result split by profile contract.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CapabilityContract {
    Native(NativeCapabilityContract),
    Embedded(EmbeddedCapabilityContract),
}
impl NativeCapabilityContract {
    pub(crate) fn from_platform_caps(caps: PlatformCapabilities) -> Self {
        Self {
            dpi_scaling: caps.dpi_scaling,
            ime: caps.ime,
            accessibility: caps.accessibility,
            native_menu: caps.native_menu,
            typed_widget_trigger: caps.typed_widget_trigger,
        }
    }
}
/// Platform backend contract used by widget/runtime layers.
///
/// Core lifecycle methods are required. Optional capabilities (IME,
/// accessibility, drag-and-drop) have default no-op implementations
/// on the Platform trait itself — backends override them when supported.
pub trait Platform: Send + Sync {
    /// Returns self as a `&dyn Any` for downcasting.
    fn as_any(&self) -> &dyn core::any::Any {
        // Safe fallback — unsized coercion on a unit type avoids panicking.
        // Concrete backends should override with a self-referencing impl.
        static UNIT: () = ();
        &UNIT as &dyn core::any::Any
    }
    /// Returns the mobile backend extension when this platform drives a mobile
    /// native view.
    ///
    /// Mobile runtimes (Android/iOS) override this so the `mobile-*` runtime
    /// helpers configure the *same* platform instance that `get_platform()`
    /// returns, instead of a separate preview singleton. Desktop/stub backends
    /// keep the default `None`.
    #[cfg(feature = "mobile-api")]
    fn mobile_extension(&self) -> Option<&dyn MobilePlatformExtension> {
        None
    }
    /// Returns backend identifier string.
    fn backend_name(&self) -> &'static str;
    /// Returns platform family classification.
    fn family(&self) -> PlatformFamily;
    /// Runtime capabilities exposed by the current backend.
    fn capabilities(&self) -> PlatformCapabilities {
        let desktop = matches!(self.family(), PlatformFamily::Desktop);
        PlatformCapabilities {
            dpi_scaling: desktop,
            ime: desktop,
            accessibility: desktop,
            native_menu: desktop,
            typed_widget_trigger: true,
        }
    }
    /// Native capability contract published by desktop-capable runtimes.
    fn native_capability_contract(&self) -> Option<NativeCapabilityContract> {
        if matches!(self.family(), PlatformFamily::Desktop) {
            Some(NativeCapabilityContract::from_platform_caps(self.capabilities()))
        } else {
            None
        }
    }
    /// Embedded capability contract published by constrained runtimes.
    fn embedded_capability_contract(&self) -> Option<EmbeddedCapabilityContract> {
        if matches!(self.family(), PlatformFamily::Embedded) {
            Some(EmbeddedCapabilityContract {
                fixed_dpi: self.dpi_scale_factor() == 1.0,
                low_memory_mode: true,
                typed_widget_trigger: self.capabilities().typed_widget_trigger,
            })
        } else {
            None
        }
    }
    /// Logical DPI scale factor for coordinate transforms.
    fn dpi_scale_factor(&self) -> f32 {
        1.0
    }
    fn init(&self);
    fn run(&self);
    fn quit(&self);

    /// Destroy a widget and release the resources associated with it.
    ///
    /// Returns `true` when the widget existed and was torn down.
    ///
    /// Implementations must release **everything** they registered for the
    /// widget: the backend state record, any native-object registry entry (and
    /// where the platform requires it, the underlying OS object itself), and any
    /// per-widget side tables (list/combo box items, selections, menu ownership).
    ///
    /// # Long-running applications
    ///
    /// Before this method existed, a backend's registries could only grow: a UI
    /// that is rebuilt (create/discard cycles) leaked one state record plus one
    /// native handle per discarded widget, without bound. A 8000-widget churn
    /// loop measured +49 MB RSS on the macOS objc2 backend.
    ///
    /// The default implementation returns `false` so that third-party backends
    /// written against an earlier version keep compiling; every in-tree backend
    /// overrides it.
    fn destroy_widget(&self, _widget_id: ObjectId) -> bool {
        false
    }

    /// Mounts a **self-drawn** widget into a native window.
    ///
    /// # Why this is one method and not one per widget kind
    ///
    /// The native `create_*` methods each map onto a real OS control. Widgets
    /// that paint themselves through [`crate::widget::Draw`] have no OS control
    /// to map to, so there is nothing for a per-kind constructor to do. What the
    /// backend owes such a widget is exactly one thing: a native surface that
    /// calls back into the process-wide widget registry whenever the OS wants a
    /// repaint. `mount_self_drawn` is that surface.
    ///
    /// The caller registers the widget first
    /// ([`crate::widget::runtime::register`]) and passes the resulting id here
    /// together with the parent window and the desired rectangle. The backend
    /// must not take ownership of the widget: it lives in the registry for as
    /// long as the mount exists.
    ///
    /// # Return value
    ///
    /// `true` when a native surface was created and will be repainted from the
    /// registry. `false` when this backend cannot display self-drawn content —
    /// the default below. Callers must treat `false` as "cannot display here"
    /// and say so, rather than showing an empty window.
    ///
    /// # Backends
    ///
    /// * macOS (`cocoa`) — an `NSView` subclass whose `drawRect:` blits a frame.
    /// * Windows (`winapi`) — a child `HWND` painted from `WM_PAINT`.
    /// * Linux (`gtk-native`) — a `gtk::DrawingArea` painted from `connect_draw`.
    /// * HarmonyOS — awaits the OpenHarmony SDK; returns `false` until then.
    fn mount_self_drawn(&self, _parent: ObjectId, _id: ObjectId, _rect: crate::core::Rect) -> bool {
        false
    }

    /// Updates the rectangle of a previously mounted self-drawn widget.
    ///
    /// Returns `false` when `id` is not mounted on this backend.
    fn resize_self_drawn(&self, _id: ObjectId, _rect: crate::core::Rect) -> bool {
        false
    }

    /// Unmounts a self-drawn widget and releases its native surface.
    ///
    /// The widget stays in the process-wide registry; the caller decides when to
    /// drop it via [`crate::widget::runtime::unregister`].
    ///
    /// Returns `false` when `id` is not mounted on this backend.
    fn unmount_self_drawn(&self, _id: ObjectId) -> bool {
        false
    }

    /// Marks a mounted self-drawn widget as needing a repaint.
    ///
    /// Returns `false` when `id` is not mounted on this backend. Backends that
    /// do not implement it keep the default so unmounted ids stay a no-op.
    fn repaint_self_drawn(&self, _id: ObjectId) -> bool {
        false
    }

    /// Returns `true` when this backend can display self-drawn widgets.
    ///
    /// Backends report `true` only once [`Platform::mount_self_drawn`] is
    /// actually implemented, so hosts can ask before building a UI that they
    /// would not be able to display.
    fn supports_self_drawn(&self) -> bool {
        false
    }

    /// Renders a shortcut in the notation this operating system uses in menus.
    ///
    /// macOS returns `⌘⇧Z`; Windows and Linux return `Ctrl+Shift+Z`. Callers use
    /// this for menu labels and tooltips so a single shortcut table reads
    /// natively everywhere, with no `cfg` in application code.
    ///
    /// This covers *display* only. Whether the accelerator is actually wired up
    /// to fire is [`Platform::menu_add_item`]'s responsibility.
    fn format_shortcut(&self, shortcut: &crate::shortcut::Shortcut) -> String {
        crate::shortcut::format_shortcut_for_platform(shortcut, self.shortcut_style())
    }

    /// How this backend's operating system spells shortcut glyphs.
    ///
    /// Lets the notation follow the *backend* rather than a compile-time `cfg` in
    /// the shortcut layer: the macOS backends answer `Mac` (`⌘⇧Z`) and every other
    /// backend answers `Desktop` (`Ctrl+Shift+Z`). The default derives from the
    /// build target so backends with no opinion — including out-of-tree ones — stay
    /// correct.
    ///
    /// See principle #35: menu notation is presented through a runtime query, not a
    /// `cfg!(target_os)` check in a middle layer.
    fn shortcut_style(&self) -> crate::shortcut::PlatformShortcutStyle {
        crate::shortcut::PlatformShortcutStyle::current()
    }

    /// Total physical memory installed on this machine, in mebibytes.
    ///
    /// Upper layers (menu/GPU adaptivity) need the *machine* memory to size
    /// their caches, and that figure is only obtainable through the host OS:
    /// `/proc/meminfo` on Linux, `sysctl hw.memsize` on macOS,
    /// `GlobalMemoryStatusEx` on Windows. Probing it in a middle layer would
    /// violate the platform-isolation rule (principle #36), so every backend
    /// answers here instead.
    ///
    /// Returns `None` when this backend cannot determine the value. Callers
    /// must treat `None` as "unknown" and degrade honestly — never substitute a
    /// made-up constant such as `4096`.
    fn total_memory_mb(&self) -> Option<u64> {
        None
    }

    /// Whether the machine is currently drawing power from its battery.
    ///
    /// Desktop towers and servers report `false`. Backends on hardware without
    /// a battery also report `false` — the question is "is a battery draining",
    /// not "does a battery exist". Platforms that cannot tell return `false`,
    /// which selects the *non*-throttled defaults; that is the safe direction,
    /// because a wrong "on battery" would silently strip animations.
    fn is_on_battery(&self) -> bool {
        false
    }

    /// This process's resident memory as a fraction of its reserved address
    /// space, clamped to `[0.0, 1.0]`.
    ///
    /// Used by the adaptive-quality monitor to decide when to shed caches. The
    /// figure comes from OS process accounting — `/proc/self/status`
    /// (`VmRSS`/`VmSize`) on Linux, `proc_pidinfo`/`ps` on macOS,
    /// `GetProcessMemoryInfo` on Windows — so it is answered by the backend and
    /// never probed from a middle layer (principle #36).
    ///
    /// Returns `None` when this backend has no process-memory source; callers
    /// treat that as "unknown" rather than zero.
    fn process_memory_utilization(&self) -> Option<f32> {
        None
    }

    /// This process's CPU utilization as a fraction `[0.0, 1.0]`.
    ///
    /// Like [`Platform::process_memory_utilization`], this is obtained from OS
    /// process accounting and therefore lives behind the backend. Returns `None`
    /// when the backend has no reliable source; callers must not interpret that
    /// as an idle system.
    fn process_cpu_utilization(&self) -> Option<f32> {
        None
    }

    /// Hands a rendered print job to the OS print subsystem.
    ///
    /// The job is passed as a file already serialized in the platform's own
    /// job format. Each backend invokes whatever mechanism its OS provides:
    /// `lpr`/`lp` on macOS and Linux, the shell `Print` verb on Windows. The
    /// file's lifetime is owned by the caller, which deletes it after this
    /// returns; the implementation must not retain the path.
    ///
    /// Returns `Err` with a human-readable reason when no print mechanism is
    /// available or all of them failed, so the caller can report it instead of
    /// pretending the job printed.
    fn spawn_print_job(&self, job_file: &std::path::Path) -> Result<(), String> {
        let _ = job_file;
        Err("system print backend is not supported on this platform".to_string())
    }

    /// Whether the OS exposes a print spooler this backend can submit to.
    ///
    /// `PrintDialog::show` asks this before claiming a job can be printed, so a
    /// host without a spooler gets a truthful `false` instead of a dialog that
    /// silently discards the document. Probing for `lp`/`lpr`/`print` is an OS
    /// concern and therefore lives in the backend (principle #36).
    ///
    /// The default is `false`; backends with a spooler override it.
    fn has_print_support(&self) -> bool {
        false
    }

    /// Native widget kinds this backend can construct as real OS controls.
    ///
    /// Control routing asks this instead of testing `cfg(target_os)`: a backend
    /// reports the primitives it actually implements (`SysListView32` on Windows,
    /// for instance), and everything not listed falls back to the custom-painted
    /// backend. This keeps the routing table free of per-OS branches while still
    /// letting a platform promote kinds as its native coverage grows
    /// (principle #36).
    ///
    /// The default is empty: a backend that publishes nothing routes every kind
    /// through the global policy table.
    fn native_widget_kinds(&self) -> &'static [crate::widget::WidgetKind] {
        &[]
    }

    /// Creates a native web engine view, when this backend can host one.
    ///
    /// Returns `None` on backends with no embeddable engine (or no display), which
    /// tells `src/web/` to use its simulated navigation path. The concrete engine
    /// type is a backend-private implementation detail; callers only ever see
    /// [`NativeWebEngine`], so no platform crate is named above this layer
    /// (principle #36).
    ///
    /// The default is `None`; backends with a real engine override it.
    fn create_web_engine(&self) -> Option<Box<dyn NativeWebEngine>> {
        None
    }

    /// Translates a shortcut into the backend's own accelerator representation.
    ///
    /// Returns `None` when this backend has no accelerator support, or when the
    /// shortcut uses a key the backend cannot express. Backends override this
    /// only when registering a menu item needs a representation other than the
    /// displayed text (for example a Win32 `ACCEL` table entry).
    fn parse_shortcut(&self, _shortcut: &crate::shortcut::Shortcut) -> Option<String> {
        None
    }

    fn create_window(&self, title: &str, x: i32, y: i32, width: u32, height: u32) -> ObjectId;
    fn create_button(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_checkbox(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_line_edit(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_label(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_radio_button(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_slider(&self, parent: ObjectId, x: i32, y: i32, width: u32, height: u32) -> ObjectId;
    fn create_progress_bar(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_combo_box(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn combo_box_add_item(&self, combo_box: ObjectId, _text: &str) -> bool;
    fn combo_box_clear_items(&self, combo_box: ObjectId) -> bool;
    fn combo_box_set_current_index(&self, combo_box: ObjectId, index: usize) -> bool;
    fn combo_box_current_index(&self, combo_box: ObjectId) -> Option<usize>;
    fn combo_box_item_count(&self, combo_box: ObjectId) -> usize;
    fn combo_box_item_text(&self, combo_box: ObjectId, index: usize) -> Option<String>;
    fn create_list_box(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn list_box_add_item(&self, list_box: ObjectId, text: &str) -> bool;
    fn list_box_remove_item(&self, list_box: ObjectId, index: usize) -> bool;
    fn list_box_clear_items(&self, list_box: ObjectId) -> bool;
    fn list_box_set_current_index(&self, list_box: ObjectId, index: usize) -> bool;
    fn list_box_current_index(&self, list_box: ObjectId) -> Option<usize>;
    fn list_box_item_count(&self, list_box: ObjectId) -> usize;
    fn list_box_item_text(&self, list_box: ObjectId, index: usize) -> Option<String>;
    fn create_panel(&self, parent: ObjectId, x: i32, y: i32, width: u32, height: u32) -> ObjectId;
    fn create_menu_bar(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_menu(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn attach_menu_bar_to_window(&self, window: ObjectId, menu_bar: ObjectId) -> bool;
    /// Adds an item to a menu.
    ///
    /// # `shortcut`
    ///
    /// This parameter is the shortcut **as it should be displayed**:
    /// `"⌘⇧Z"` on macOS, `"Ctrl+Shift+Z"` on Windows and Linux. Passing `None`
    /// (or `""`) adds a plain item with no accelerator.
    ///
    /// Note the asymmetry with the rest of this crate, where an application
    /// action is declared once with a typed [`crate::shortcut::Shortcut`] and the
    /// platform decides its notation. A display string is the right contract for
    /// *this* method because the text is bound to a concrete menu item on one
    /// concrete OS: building it here keeps the platform-specific spelling out of
    /// the caller, and lets platforms that register accelerators separately (for
    /// example a Win32 `ACCEL` table) parse the text instead of re-deriving it.
    fn menu_add_item(&self, parent_menu: ObjectId, text: &str, shortcut: Option<&str>) -> ObjectId;
    /// Returns the accelerator display text bound to a menu item.
    ///
    /// `None` when the id is not a menu item or it has no accelerator. Useful to
    /// assert that a shortcut was actually registered, rather than only rendered
    /// into a label.
    fn menu_item_shortcut(&self, _menu_item: ObjectId) -> Option<String> {
        None
    }
    /// Returns the backend's native handle for a widget, if it has one.
    ///
    /// The value is opaque and backend-specific: it is the platform's own object
    /// pointer or handle (`NSView*` on macOS, `HWND` on Windows, ...), not a
    /// cross-platform type. Backends that keep only logical state return `None`,
    /// which is also the answer for widgets created off the UI thread.
    ///
    /// This is the escape hatch for host code and integration tests that need to
    /// reach the underlying control; it must not be used for routine widget work.
    fn get_native_handle(&self, _widget: ObjectId) -> Option<usize> {
        None
    }
    fn poll_menu_triggered(&self) -> Option<ObjectId>;
    fn inject_menu_trigger(&self, menu_item_id: ObjectId) -> bool;
    fn poll_widget_triggered(&self) -> Option<ObjectId>;
    fn poll_widget_trigger_event(&self) -> Option<WidgetTriggerEvent>;
    fn inject_widget_trigger_event(&self, widget_id: ObjectId, kind: WidgetTriggerKind) -> bool;
    fn create_tool_bar(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_status_bar(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    #[allow(clippy::too_many_arguments)]
    fn create_message_box(
        &self,
        parent: ObjectId,
        title: &str,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_file_dialog(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_color_dialog(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_font_dialog(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_spin_box(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_list_view(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;
    fn create_scroll_area(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;

    /// Create a labelled group frame (a real border+label container where the
    /// platform provides one).
    ///
    /// Backends without a dedicated group primitive return a plain panel; the
    /// hybrid route sends `WidgetKind::GroupBox` to the self-drawn backend, so
    /// this method only needs to be meaningful for `NativePreferred` callers.
    fn create_group_box(
        &self,
        parent: ObjectId,
        title: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;

    /// Create a plain bordered frame container.
    fn create_frame(&self, parent: ObjectId, x: i32, y: i32, width: u32, height: u32) -> ObjectId;

    /// Create a tabbed container.
    fn create_tab_widget(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;

    /// Create a draggable splitter (two panes with a movable divider).
    fn create_splitter(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;

    /// Create a toggle button (a button with a persistent active state).
    fn create_toggle_button(
        &self,
        parent: ObjectId,
        text: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;

    /// Create a calendar view.
    fn create_calendar(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;

    /// Create a scroll bar (a scrollbar control with an adjustment model).
    fn create_scroll_bar(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;

    /// Create a fractional (double) spin box.
    fn create_double_spin_box(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;

    /// Create a font-family combo box.
    fn create_font_combo_box(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;

    /// Create a context (popup) menu: a menu shown on demand rather than
    /// attached to a menu bar.
    fn create_context_menu(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;

    /// Create a transient popup window.
    fn create_popup_window(
        &self,
        parent: ObjectId,
        title: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;

    /// Create a generic dialog window (title + content area).
    fn create_dialog(
        &self,
        parent: ObjectId,
        title: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;

    /// Create an input dialog.
    fn create_input_dialog(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;

    /// Create a progress dialog.
    fn create_progress_dialog(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;

    /// Create a directory (folder) chooser dialog.
    fn create_directory_dialog(
        &self,
        parent: ObjectId,
        title: &str,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;

    /// Create a date picker.
    fn create_date_picker(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;

    /// Create a time picker.
    fn create_time_picker(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;

    /// Create a combined date+time picker.
    fn create_date_time_picker(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;

    /// Create a busy/activity indicator (indeterminate progress).
    fn create_activity_indicator(
        &self,
        parent: ObjectId,
        x: i32,
        y: i32,
        width: u32,
        height: u32,
    ) -> ObjectId;

    fn show_widget(&self, widget_id: ObjectId);
    fn hide_widget(&self, widget_id: ObjectId);
    fn set_widget_geometry(&self, widget_id: ObjectId, x: i32, y: i32, width: u32, height: u32);
    fn set_widget_text(&self, widget_id: ObjectId, text: &str);
    fn get_widget_text(&self, widget_id: ObjectId) -> String;
    fn set_widget_enabled(&self, widget_id: ObjectId, enabled: bool);
    fn is_widget_enabled(&self, widget_id: ObjectId) -> bool;
    fn set_widget_visible(&self, widget_id: ObjectId, visible: bool);
    fn is_widget_visible(&self, widget_id: ObjectId) -> bool;

    // ─────────────────────────────────────────────────────────────
    // Uniform native-control properties (one API, every OS)
    // ─────────────────────────────────────────────────────────────
    //
    // Native controls carry more state than text: a slider has a value and a
    // range, a combo box has a selected index, a checkbox has a checked state.
    // Before these methods existed the only OS-independent way to reach that
    // state was [`Platform::set_widget_text`], which (on backends that support
    // it) parses the string into a number — lossy for any control whose payload
    // is not its display text, and unavailable for selection indices.
    //
    // These methods unify the *shape* of the call, not the capabilities of the
    // controls. Each backend maps them onto whatever its own native control
    // actually exposes and reports honestly when it cannot (see below). The
    // point is that a caller writes **one** expression — `set_widget_value(id,
    // v)` — and it compiles and runs on every OS without `cfg(target_os)` or a
    // per-OS `if`/`else`, which is the whole purpose of this trait (principle
    // #35/#36).
    //
    // # Per-OS capability differences are allowed
    //
    // A control may be value-carrying on one OS and not on another; that is a
    // genuine platform difference, not a defect. The defaults return `false` /
    // `None` — never a made-up value — so a backend that has no such property
    // reports it as *absent* (principle #37) and the caller branches on the
    // result at runtime if it cares. What is forbidden is a backend pretending
    // a write took effect when nothing changed.

    /// Set a control's primary numeric value (slider, progress bar, spin box,
    /// scroll bar, dial, ... wherever the OS control has one).
    ///
    /// Returns `true` when the backend wrote the value to a real native control
    /// (or an authoritative state model). Returns `false` when this backend's
    /// control has no numeric value, or the widget id is unknown; the caller
    /// must treat `false` as "the value did not change".
    fn set_widget_value(&self, _widget_id: ObjectId, _value: f64) -> bool {
        false
    }

    /// Read a control's primary numeric value.
    ///
    /// `None` when this backend's control has no numeric value (unknown id, or
    /// a control without one). When it returns `Some`, the value must reflect
    /// what the native control actually holds, not a cached default.
    fn widget_value(&self, _widget_id: ObjectId) -> Option<f64> {
        None
    }

    /// Set a control's `(min, max)` range (slider, spin box, scroll bar).
    ///
    /// Returns `false` when this backend's control has no range or the widget id
    /// is unknown. Clamping the current value against the new range is the
    /// backend's job, exactly as the native control does it.
    fn set_widget_range(&self, _widget_id: ObjectId, _min: f64, _max: f64) -> bool {
        false
    }

    /// Read a control's `(min, max)` range.
    fn widget_range(&self, _widget_id: ObjectId) -> Option<(f64, f64)> {
        None
    }

    /// Set a control's selection index (combo box, list box, tab widget).
    ///
    /// `index == None` clears the selection where this OS control supports it.
    /// Returns `false` when this backend's control has no selection model, the
    /// id is unknown, or the index is out of bounds.
    fn set_widget_selected_index(&self, _widget_id: ObjectId, _index: Option<usize>) -> bool {
        false
    }

    /// Read a control's current selection index.
    fn widget_selected_index(&self, _widget_id: ObjectId) -> Option<usize> {
        None
    }

    /// Set a checkable control's checked state (check box, radio button, toggle
    /// button).
    ///
    /// Returns `false` when this backend's control is not checkable or the id is
    /// unknown.
    fn set_widget_checked(&self, _widget_id: ObjectId, _checked: bool) -> bool {
        false
    }

    /// Read a checkable control's checked state.
    fn is_widget_checked(&self, _widget_id: ObjectId) -> Option<bool> {
        None
    }

    /// Set a control's increment step (slider, spin box, scroll bar).
    ///
    /// The step is how far a single keyboard/arrow interaction moves the value.
    /// Returns `false` when this backend's control has no settable step (a
    /// progress bar, for example) or the id is unknown.
    fn set_widget_step(&self, _widget_id: ObjectId, _step: f64) -> bool {
        false
    }

    /// Read a control's increment step.
    fn widget_step(&self, _widget_id: ObjectId) -> Option<f64> {
        None
    }

    /// Set an indeterminate (busy) state on a progress-style control.
    ///
    /// The three desktop toolkits all express this natively — AppKit
    /// `setIndeterminate:`, Win32 `PBS_MARQUEE`, GTK `pulse()` — so the control
    /// animates instead of showing a fixed fraction. Returns `false` when this
    /// backend's control has no indeterminate mode or the id is unknown.
    fn set_widget_indeterminate(&self, _widget_id: ObjectId, _indeterminate: bool) -> bool {
        false
    }

    /// Read a progress-style control's indeterminate state.
    fn is_widget_indeterminate(&self, _widget_id: ObjectId) -> Option<bool> {
        None
    }

    /// Set a text-entry control's read-only state.
    ///
    /// AppKit uses `setEditable:`, Win32 `EM_SETREADONLY`, GTK
    /// `set_editable(false)`. Returns `false` when this backend's control is not
    /// a text entry or the id is unknown.
    fn set_widget_read_only(&self, _widget_id: ObjectId, _read_only: bool) -> bool {
        false
    }

    /// Read a text-entry control's read-only state.
    fn is_widget_read_only(&self, _widget_id: ObjectId) -> Option<bool> {
        None
    }

    /// Set a text-entry control's maximum accepted length in characters.
    ///
    /// Win32 uses `EM_SETLIMITTEXT` and GTK `set_max_length`; AppKit's
    /// `NSTextField` has no direct equivalent (it is enforced through a delegate),
    /// so the macOS backend honestly returns `false` here. Callers that need the
    /// limit on every OS must enforce it themselves.
    fn set_widget_max_length(&self, _widget_id: ObjectId, _max_length: u32) -> bool {
        false
    }

    /// Read a text-entry control's maximum accepted length.
    fn widget_max_length(&self, _widget_id: ObjectId) -> Option<u32> {
        None
    }

    /// Enable or disable IME input handling for a widget.
    fn set_widget_ime_enabled(&self, _widget_id: ObjectId, _enabled: bool) -> bool {
        false
    }
    /// Query IME enabled state for a widget.
    fn is_widget_ime_enabled(&self, _widget_id: ObjectId) -> bool {
        false
    }
    /// Returns a reference to the platform's IME bridge, if available.
    fn ime_bridge(&self) -> Option<&dyn crate::platform::ime::ImeBridge> {
        None
    }
    /// Set accessibility name/label for a widget.
    fn set_widget_accessibility_name(&self, _widget_id: ObjectId, _name: &str) -> bool {
        false
    }
    /// Read accessibility name/label for a widget.
    fn get_widget_accessibility_name(&self, _widget_id: ObjectId) -> String {
        String::new()
    }
    /// Returns a reference to the platform's accessibility bridge, if available.
    fn accessibility_bridge(
        &self,
    ) -> Option<&dyn crate::platform::accessibility::AccessibilityBridge> {
        None
    }

    /// Returns a reference to the platform's rich clipboard backend, if available.
    fn clipboard_backend(&self) -> Option<&dyn crate::platform::clipboard::RichClipboardBackend> {
        None
    }
    /// Set plain text clipboard content.
    fn set_clipboard_text(&self, _text: &str) -> bool {
        false
    }
    /// Read plain text clipboard content.
    fn get_clipboard_text(&self) -> String {
        String::new()
    }
    /// Start a drag operation from source widget.
    fn begin_drag(&self, _source_widget_id: ObjectId, _mime: &str, _payload: &[u8]) -> bool {
        false
    }
    /// Poll next drop event if available.
    fn poll_drop_event(&self) -> Option<DropEvent> {
        None
    }
    /// Inject drop event into backend queue.
    fn inject_drop_event(&self, _event: DropEvent) -> bool {
        false
    }
}
/// Optional mobile-specific extension contract.
pub trait MobilePlatformExtension: Send + Sync {
    /// Returns the active mobile backend family.
    fn mobile_backend(&self) -> MobileBackend;
    /// Attaches runtime to an externally provided native view handle.
    fn attach_to_native_view(&self, _native_handle: usize) -> bool;
}

#[derive(Debug)]
pub(crate) struct MenuNodeState {
    pub(crate) text: String,
}
