//! New widget types — popular modern UI controls and mobile-first widgets.
//!
//! This module contains widgets added as part of the BLUE11 improvement plan (R10).
//! These include popular UI patterns (Switch, SearchBox, Chip, Badge, etc.) and
//! mobile-first widgets (BottomSheet, NavigationDrawer, AppBar, etc.).
#[cfg(not(feature = "mini"))]
pub mod adaptive_scaffold;
pub mod animated_image;
#[cfg(not(feature = "mini"))]
pub mod app_bar;
#[cfg(not(feature = "mini"))]
pub mod audio_visualizer;
#[cfg(not(feature = "mini"))]
pub mod auto_complete_edit;
#[cfg(not(feature = "mini"))]
pub mod avatar;
#[cfg(not(feature = "mini"))]
pub mod badge;
#[cfg(not(feature = "mini"))]
pub mod bar_chart;
#[cfg(not(feature = "mini"))]
pub mod barcode_scanner;
#[cfg(not(feature = "mini"))]
pub mod bezier_curve_editor;
#[cfg(not(feature = "mini"))]
pub mod bottom_navigation_bar;
#[cfg(not(feature = "mini"))]
pub mod bottom_sheet;
#[cfg(not(feature = "mini"))]
pub mod camera_preview;
#[cfg(not(feature = "mini"))]
pub mod carousel;
#[cfg(not(feature = "mini"))]
pub mod chip;
#[cfg(not(feature = "mini"))]
pub mod color_history;
#[cfg(not(feature = "mini"))]
pub mod color_well;
#[cfg(not(feature = "mini"))]
pub mod cupertino;
#[cfg(not(feature = "mini"))]
pub mod cupertino_date_picker;
#[cfg(not(feature = "mini"))]
pub mod cupertino_nav_bar;
#[cfg(not(feature = "mini"))]
pub mod cupertino_segmented_control;
#[cfg(not(feature = "mini"))]
pub mod date_range_picker;
#[cfg(not(feature = "mini"))]
pub mod divider;
#[cfg(not(feature = "mini"))]
pub mod dropdown_menu;
#[cfg(not(feature = "mini"))]
pub mod editable_combo_box;
#[cfg(not(feature = "mini"))]
pub mod empty_state;
#[cfg(not(feature = "mini"))]
pub mod fab;
#[cfg(not(feature = "mini"))]
pub mod find_replace_dialog;
#[cfg(not(feature = "mini"))]
pub mod floating_label;
#[cfg(not(feature = "mini"))]
pub mod font_preview;
#[cfg(not(feature = "mini"))]
pub mod hero_animation;
#[cfg(not(feature = "mini"))]
pub mod icon;
#[cfg(not(feature = "mini"))]
pub mod image_gallery;
#[cfg(not(feature = "mini"))]
pub mod ime_preedit;
#[cfg(not(feature = "mini"))]
pub mod inplace_editor;
#[cfg(not(feature = "mini"))]
pub mod line_chart;
#[cfg(not(feature = "mini"))]
pub mod lottie_widget;
#[cfg(not(feature = "mini"))]
pub mod masked_edit;
#[cfg(not(feature = "mini"))]
pub mod masonry_layout;
#[cfg(not(feature = "mini"))]
pub mod menu_button;
#[cfg(not(feature = "mini"))]
pub mod mobile_date_picker;
#[cfg(not(feature = "mini"))]
pub mod modal_bottom_sheet;
#[cfg(not(feature = "mini"))]
pub mod multi_select_combo_box;
#[cfg(not(feature = "mini"))]
pub mod navigation_drawer;
#[cfg(not(feature = "mini"))]
pub mod navigation_stack;
#[cfg(not(feature = "mini"))]
pub mod pager_page_view;
#[cfg(not(feature = "mini"))]
pub mod pie_chart;
#[cfg(not(feature = "mini"))]
pub mod popover;
#[cfg(not(feature = "mini"))]
pub mod progress_circle;
#[cfg(not(feature = "mini"))]
pub mod properties_panel;
#[cfg(not(feature = "mini"))]
pub mod property_grid;
#[cfg(not(feature = "mini"))]
pub mod pull_to_refresh;
#[cfg(not(feature = "mini"))]
pub mod qr_code;
#[cfg(not(feature = "mini"))]
pub mod range_slider;
#[cfg(not(feature = "mini"))]
pub mod rating;
#[cfg(not(feature = "mini"))]
pub mod refresh_control;
#[cfg(not(feature = "mini"))]
pub mod rive_widget;
#[cfg(not(feature = "mini"))]
pub mod safe_area;
#[cfg(not(feature = "mini"))]
pub mod search_bar;
#[cfg(not(feature = "mini"))]
pub mod search_box;
#[cfg(not(feature = "mini"))]
pub mod segmented_button;
#[cfg(not(feature = "mini"))]
pub mod shortcut_editor;
#[cfg(not(feature = "mini"))]
pub mod skeleton_loader;
#[cfg(not(feature = "mini"))]
pub mod sparkline;
#[cfg(not(feature = "mini"))]
pub mod stepper;
#[cfg(not(feature = "mini"))]
pub mod swipe_to_dismiss;
pub mod switch;
pub mod tab_view;
#[cfg(not(feature = "mini"))]
pub mod tag_input;
#[cfg(not(feature = "mini"))]
pub mod tooltip;
#[cfg(not(feature = "mini"))]
pub mod video_player;
#[cfg(not(feature = "mini"))]
pub mod wizard;
// Re-exports
#[cfg(not(feature = "mini"))]
pub use adaptive_scaffold::AdaptiveScaffold;
pub use animated_image::{AnimatedFrame, AnimatedImage, AnimatedImageFormat};
#[cfg(not(feature = "mini"))]
pub use app_bar::AppBar;
#[cfg(not(feature = "mini"))]
pub use audio_visualizer::AudioVisualizer;
#[cfg(not(feature = "mini"))]
pub use auto_complete_edit::AutoCompleteEdit;
#[cfg(not(feature = "mini"))]
pub use avatar::Avatar;
#[cfg(not(feature = "mini"))]
pub use badge::Badge;
#[cfg(not(feature = "mini"))]
pub use bar_chart::{BarChart, BarEntry};
#[cfg(not(feature = "mini"))]
pub use barcode_scanner::{BarcodeFormat, BarcodeResult, BarcodeScanner};
#[cfg(not(feature = "mini"))]
pub use bezier_curve_editor::BezierCurveEditor;
#[cfg(not(feature = "mini"))]
pub use bottom_navigation_bar::BottomNavigationBar;
#[cfg(not(feature = "mini"))]
pub use bottom_navigation_bar::NavItem;
#[cfg(not(feature = "mini"))]
pub use bottom_sheet::BottomSheet;
#[cfg(not(feature = "mini"))]
pub use camera_preview::CameraPreview;
#[cfg(not(feature = "mini"))]
pub use carousel::Carousel;
#[cfg(not(feature = "mini"))]
pub use carousel::CarouselPage;
#[cfg(not(feature = "mini"))]
pub use chip::Chip;
#[cfg(not(feature = "mini"))]
pub use color_history::ColorHistory;
#[cfg(not(feature = "mini"))]
pub use color_well::ColorWell;
#[cfg(not(feature = "mini"))]
pub use cupertino::CupertinoAlertDialog;
#[cfg(not(feature = "mini"))]
pub use cupertino::CupertinoSlider;
#[cfg(not(feature = "mini"))]
pub use cupertino::CupertinoSwitch;
#[cfg(not(feature = "mini"))]
pub use cupertino::MaterialNavigationRail;
#[cfg(not(feature = "mini"))]
pub use cupertino::MaterialSnackbar;
#[cfg(not(feature = "mini"))]
pub use cupertino::RailItem;
#[cfg(not(feature = "mini"))]
pub use cupertino_date_picker::CupertinoDatePicker;
#[cfg(not(feature = "mini"))]
pub use cupertino_nav_bar::CupertinoNavigationBar;
#[cfg(not(feature = "mini"))]
pub use cupertino_segmented_control::CupertinoSegmentedControl;
#[cfg(not(feature = "mini"))]
pub use date_range_picker::DateRangePicker;
#[cfg(not(feature = "mini"))]
pub use divider::Divider;
#[cfg(not(feature = "mini"))]
pub use dropdown_menu::{DropdownItem, DropdownMenu};
#[cfg(not(feature = "mini"))]
pub use editable_combo_box::EditableComboBox;
#[cfg(not(feature = "mini"))]
pub use empty_state::EmptyState;
#[cfg(not(feature = "mini"))]
pub use fab::FAB;
#[cfg(not(feature = "mini"))]
pub use find_replace_dialog::FindReplaceDialog;
#[cfg(not(feature = "mini"))]
pub use floating_label::FloatingLabel;
#[cfg(not(feature = "mini"))]
pub use font_preview::FontPreview;
#[cfg(not(feature = "mini"))]
pub use hero_animation::HeroAnimation;
#[cfg(not(feature = "mini"))]
pub use icon::Icon;
#[cfg(not(feature = "mini"))]
pub use icon::IconName;
#[cfg(not(feature = "mini"))]
pub use image_gallery::{GalleryImage, ImageGallery};
#[cfg(not(feature = "mini"))]
pub use ime_preedit::ImePreedit;
#[cfg(not(feature = "mini"))]
pub use inplace_editor::InplaceEditor;
#[cfg(not(feature = "mini"))]
pub use line_chart::LineChart;
#[cfg(not(feature = "mini"))]
pub use lottie_widget::LottieWidget;
#[cfg(not(feature = "mini"))]
pub use masked_edit::MaskedEdit;
#[cfg(not(feature = "mini"))]
pub use masonry_layout::{MasonryItem, MasonryLayout};
#[cfg(not(feature = "mini"))]
pub use menu_button::{MenuButton, MenuItem};
#[cfg(not(feature = "mini"))]
pub use mobile_date_picker::MobileDatePicker;
#[cfg(not(feature = "mini"))]
pub use modal_bottom_sheet::ModalBottomSheet;
#[cfg(not(feature = "mini"))]
pub use multi_select_combo_box::MultiSelectComboBox;
#[cfg(not(feature = "mini"))]
pub use multi_select_combo_box::MultiSelectItem;
#[cfg(not(feature = "mini"))]
pub use navigation_drawer::NavigationDrawer;
#[cfg(not(feature = "mini"))]
pub use navigation_stack::NavigationEvent;
#[cfg(not(feature = "mini"))]
pub use navigation_stack::NavigationStack;
#[cfg(not(feature = "mini"))]
pub use pager_page_view::PagerPageView;
#[cfg(not(feature = "mini"))]
pub use pie_chart::PieChart;
#[cfg(not(feature = "mini"))]
pub use popover::Popover;
#[cfg(not(feature = "mini"))]
pub use progress_circle::ProgressCircle;
#[cfg(not(feature = "mini"))]
pub use properties_panel::{PropertiesPanel, PropertyEntry, PropertyValue};
#[cfg(not(feature = "mini"))]
pub use property_grid::{PropertyGrid, PropertyItem};
#[cfg(not(feature = "mini"))]
pub use pull_to_refresh::PullToRefresh;
#[cfg(not(feature = "mini"))]
pub use qr_code::QRCode;
#[cfg(not(feature = "mini"))]
pub use range_slider::RangeSlider;
#[cfg(not(feature = "mini"))]
pub use range_slider::RangeSliderOrientation;
#[cfg(not(feature = "mini"))]
pub use rating::Rating;
#[cfg(not(feature = "mini"))]
pub use refresh_control::RefreshControl;
#[cfg(not(feature = "mini"))]
pub use rive_widget::{RiveInput, RiveInputValue, RiveWidget};
#[cfg(not(feature = "mini"))]
pub use safe_area::{SafeArea, SafeAreaInsets};
#[cfg(not(feature = "mini"))]
pub use search_bar::SearchBar;
#[cfg(not(feature = "mini"))]
pub use search_box::SearchBox;
#[cfg(not(feature = "mini"))]
pub use segmented_button::Segment;
#[cfg(not(feature = "mini"))]
pub use segmented_button::SegmentedButton;
#[cfg(not(feature = "mini"))]
pub use shortcut_editor::ShortcutEditor;
#[cfg(not(feature = "mini"))]
pub use shortcut_editor::ShortcutEntry;
#[cfg(not(feature = "mini"))]
pub use skeleton_loader::SkeletonLoader;
#[cfg(not(feature = "mini"))]
pub use sparkline::Sparkline;
#[cfg(not(feature = "mini"))]
pub use stepper::Stepper;
#[cfg(not(feature = "mini"))]
pub use swipe_to_dismiss::SwipeToDismiss;
pub use switch::Switch;
pub use tab_view::TabPage;
pub use tab_view::TabView;
#[cfg(not(feature = "mini"))]
pub use tag_input::TagInput;
#[cfg(not(feature = "mini"))]
pub use tooltip::Tooltip;
#[cfg(not(feature = "mini"))]
pub use video_player::VideoPlayer;
#[cfg(not(feature = "mini"))]
pub use wizard::{WizardDialog, WizardStep};
